### ISSUE TITLE
Vulnerability: Issue description can lead to forged site

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#1001]
I just edited https://github.com/polarsource/polar/issues/986.

The link to fund now leads to my polar page.
I wonder: If I can setup a forged site, especially in your case, nobody would expect that this is not the original site.

![image](https://github.com/polarsource/polar/assets/564768/193ad218-2632-4918-8d15-4f1adf54123e)

A possible solution might be to create a chat bot that answers to the issue. I don't know!

**Comment by zegl** [comment]
Hey. While this might be confusing, it's not a vulnerability. As clicking the link doesn't do anything.

While the polar github app could look for and replace invalid polar-embeds, there is nothing we can do against someone embedding other images or links.
