### ISSUE TITLE
Feature flag

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1049]
I think we would benefit from feature flags now. Allowing us to develop new features quickly and ship them iteratively as we work on them without long living feature branches and to easily ship them publicly once they're fully flushed out.

Would be a nice investment to have as we start introducing more and more features in the coming months and grow the team too.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1049">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1049/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1049/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
Adding a test flag in #1076

**Comment by zegl** [comment]
This was very simple to do with PostHog! 🦔 

I've tagged our users in PostHog as `is_polar_employee` to make it easy to setup new Feature Flags for ourselves.

I setup a [feature flag called `for-you-test`](https://app.posthog.com/feature_flags/17129) that's used like this:

```diff
diff --git a/clients/apps/web/src/app/(backer)/for-you/page.tsx b/clients/apps/web/src/app/(backer)/for-you/page.tsx
index bbc16252..56d588f8 100644
--- a/clients/apps/web/src/app/(backer)/for-you/page.tsx
+++ b/clients/apps/web/src/app/(backer)/for-you/page.tsx
@@ -4,16 +4,26 @@ import IssueListItem from '@/components/Dashboard/IssueListItem'
 import Spinner from '@/components/Shared/Spinner'
 import { useAuth } from '@/hooks'
 import { useListForYouIssues } from 'polarkit/hooks'
+import { useFeatureFlagEnabled } from 'posthog-js/react'
 
 export default function Page() {
   const { currentUser } = useAuth()
 
   const issues = useListForYouIssues()
 
+  const enabled = useFeatureFlagEnabled('for-you-test')
+
   return (
     <div className="mt-2 space-y-5">
       {issues.isLoading && <Spinner />}
 
+      {enabled && (
+        <div className="bg-green-200">you&apos;re in the feature flag</div>
+      )}
+      {!enabled && (
+        <div className="bg-red-200">you&apos;re not in the feature flag</div>
+      )}
+
       {issues.data?.items?.map((issue) => (
         <IssueListItem
           issue={issue}
```

It's also possible to use the feature flag with the `<PostHogFeature>` [component](https://posthog.com/docs/libraries/react#method-2-using-the-posthogfeature-component).

Really nice stuff! Let's use this when rolling out recommendations to /feed. :-)

**Comment by zegl** [comment]
I'll close this issue, there isn't much to do on the tooling side until we have a real use case for feature flags. :)
