### ISSUE TITLE
Backer: Credit card on file

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1050]
**Dependencies:** N.A

### What
Ability for backers to store a credit card on file for easy funding of issues.

### How

**Design**
[Figma](https://www.figma.com/file/1p2oOjsRBgSrr3SC4zySJG/Polar-Latest-Design?type=design&node-id=262-9574&mode=design&t=Sdp4hiK6fY5jkGxK-0)

**Todo**
- [x] Implement support for credit card on file for backers with GitHub account
- [ ] Once magic link (email) accounts exists they should be able to use them as well

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1050">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1050/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1050/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
Fixed in #1142.

Moving leftovers to #1146
