### ISSUE TITLE
Launch updated website (maintainer focused)

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1053]
**Todo**
- [x] Update copy
- [ ] Test flow
- [ ] Launch

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1053">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1053/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1053/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Taking the liberty to close this, I think everything is done here!
