### ISSUE TITLE
Clicking the Polar logo on the dashboard crashes the page in production

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1062]
The `/` route is a NextJS proxy to the site on Framer.

For some reason, navigating to this page when the site is deployed on Vercel, breaks the site:

Somehow `/` gets translated as `/index`, and the page 404s. 

```
ApiError: Not Found
    at catchErrorCodes (/var/task/clients/apps/web/.next/server/chunks/2904.js:420:15)
    at /var/task/clients/apps/web/.next/server/chunks/2904.js:450:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://api.polar.sh/api/v1/organizations/lookup?platform=github&organization_name=index',
  status: 404,
  statusText: 'Not Found',
  body: { detail: 'Organization not found ' },
  request: {
    method: 'GET',
    url: '/api/v1/organizations/lookup',
    query: { platform: 'github', organization_name: 'index' },
    errors: { '404': 'Not Found', '422': 'Validation Error' }
  }
}
ApiError: Not Found
    at catchErrorCodes (/var/task/clients/apps/web/.next/server/chunks/2904.js:420:15)
    at /var/task/clients/apps/web/.next/server/chunks/2904.js:450:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://api.polar.sh/api/v1/organizations/lookup?platform=github&organization_name=index',
  status: 404,
  statusText: 'Not Found',
  body: { detail: 'Organization not found ' },
  request: {
    method: 'GET',
    url: '/api/v1/organizations/lookup',
    query: { platform: 'github', organization_name: 'index' },
    errors: { '404': 'Not Found', '422': 'Validation Error' }
  }
}
```

Should we replace `<Link href="/">` with `<a href="/">`?

It's annoying to debug as this works locally.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1062">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1062/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1062/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Replacing with `<a href="/">` will be a quick and easy fix. Since the website it's not generated by Next.js anyway, there isn't really benefits in using the `<Link>` component.
