### ISSUE TITLE
"GitHub" brand capitalization consistency

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1069]
I'm a bit picky on this one, but I'm particularly attached to brand capitalization 😅

Throughout the app, we sometimes use `GitHub` (the official capitalization), sometimes `Github`. It would be nice to make sure we use the official capitalization everywhere.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1069">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1069/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1069/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Agreed :) We should just to a global search-replace in one sweep.

Fun anecdote: I think I'm solely to blame here. I've always seen it as "Github". Chatted with an early employee at GitHub a month ago who schooled me about the same thing on our website and that he had to callout that it was GitHub :)
