### ISSUE TITLE
Worker is maxed out (100% CPU) for many minutes

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1081]
The worker process is currently saturated at 100% CPU for at least 20 minutes every hour. This load likely comes from our crawler jobs.

We should find a way to run crawl jobs less frequently, or in smaller batches. When the load is high, first-time-setups are slower as the jobs are put at the end of the queue.

![Screenshot 2023-09-05 at 15 42 31](https://github.com/polarsource/polar/assets/47952/f1d52f52-dba5-44dc-9bbe-f97a8a257140)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1081">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1081/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1081/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
It would be great for this kind of cases to have *priority queues*, so we can make sure important tasks (e.g. new installations, magic link email...) are always processed before less important ones like background sync.

Unfortunately, `arq` doesn't seem to have this kind of feature out-of-the-box 🤔

**Comment by zegl** [comment]
Yeah, priority queues would be cool to have! I was thinking now to see if we can horizontally scale the workers, we almost support it out of the box, the only thing missing is some sort of leader election for the cron jobs.

**Comment by frankie567** [comment]
From what I understand of the [`arq.cron` doc](https://arq-docs.helpmanual.io/#arq.cron.cron), all it does is to enqueue the job, it doesn't execute it directly. Besides, it has a `unique` option (enabled by default) that prevents multiple workers from enqueuing it several times.

So it should be safe to spawn more processes in our current state.

**Comment by zegl** [comment]
Oh, perfect!

**Comment by zegl** [comment]
This issue has been resolved for now (#1086, #1084), I'll close this issue.

We're not doing the work as often, every 12h instead of every 1h, and if we find work to do, we'll delay the work randomly up to 5 minutes. This has removed the sharp peaks in the load, and the _smearing_ of the workload means that we're never at 100% CPU anymore.

![Screenshot 2023-09-12 at 09 28 25](https://github.com/polarsource/polar/assets/47952/08c81c52-7d34-40a9-ba60-92a054828cf3)
