### ISSUE TITLE
Handle GitHub renamed and moved orgs/repos/issues

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1092]
This will be an ongoing effort, but wherever possible, start to use lookups on external_id instead of names (orgs/repos) and numbers (issues) to support moved resources.

If we encounter a resource that has been moved on GitHub's side of things, also move it on our side.

- [x] Renamed organizations
- [x] Renamed repositories
- [x] Moved repositories (new organization as owner). It's possible for an existing repository (in our DB) to be moved away from an installation to an org that doesn't have the Polar app installed, and vice versa.
- [x] Moved issues (new repo/organization as owner). When an issue is moved between repositories, the issues #number changes.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1092">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1092/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1092/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
I've started to work on this in the context of `sync_external_org_with_repo_and_issue`. Will be part of the fix for #877.

**Comment by frankie567** [comment]
The problem was encountered by a user who reported it on Discord (https://discord.com/channels/1078611507115470849/1109142435981967360/1153512562537812071).

I'll start to work on this today. Objectives:

* Handle webhook events for Renamed Organization / Transferred Repository / Transferred Issue (Renamed Repository is already handled).
* Create a migration script to fix outdated data

**Comment by frankie567** [comment]
I propose to close this for now. We have the basic bricks to handle this correctly. There are probably lot of corner cases we didn't think about, but I think they can be handled on case-by-case basis with a dedicated bug report.
