### ISSUE TITLE
Rename badge label from `polar` to `Funding`

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1102]
### What
Rename our `polar` badge label to `Fund`.

### Why
- `polar` is non-descriptive which is bad for a label
- `Fund` or equivalent has the added benefit of being clear and a CTA on the issues list standalone before the badge is shown (in issue)

### How
We should still support `polar` for legacy.
We should also support case insensitive usage of our selected word, e.g `Fund` and `fund`.

### Decision log

**Is `Fund` the right choice?**
TODO. Other options would be `Funding` or `Sponsor`. Latter is likely the most intuitive of all. However, we're using `Fund` as a term moving forward as the default so nice to keep things consistent.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1102">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1102/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1102/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Are we talking about this badge?

  </a><a href="https://polar.sh/polarsource"><img src="https://polar.sh/embed/seeks-funding-shield.svg?org=polarsource" /></a>

**Comment by birkjernstrom** [comment]
Thanks for clarifying @frankie567. No, I was referring to the labelling of issues to get the badge vs. badging all issues. Currently, the label we require is `polar` and I think `Funding` would be more self-explanatory vs. our brand name. However, we still would need to support `polar` for legacy (avoiding an update on all existing issues and their labels).

It's not a high urgency ticket, but a nice enhancement imo. Curious what you guys think @frankie567 @zegl ?

**Comment by frankie567** [comment]
Oh! Right, that makes more sense now 😄

For consistency with default GitHub tags, I think `funding` is the default we should go for:

* It's lowercased
* It's a noun (like `bug`, `enhancement`)

**Comment by zegl** [comment]
I think it makes sense, it's more clear to newcomers then "polar".

The label is only present on ~250 [currently open issues](https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3Afunding+), so the odds of conflicting with any of them is low.


The only annoyance would be for existing users that already have the "polar" label on some issues,  as they suddenly would have two labels for the same thing.

**Comment by frankie567** [comment]
> The only annoyance would be for existing users that already have the "polar" label on some issues, as they suddenly would have two labels for the same thing.

I see there is a GitHub API to update an existing label: https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#update-a-label

We could very well come up with a migration script to rename the existing label.

**Comment by birkjernstrom** [comment]
Let's use the label `Fund`.

Regarding historical issues and a potential migration script. I think we should avoid this and only do it separately standalone in the future if needed/wanted. Two reasons:

1. I don't like the idea of changing something on a public maintainer surface without them being aware upfront. Super low risk of any maintainer being against this change (I think it would be a welcome one), but I would feel uncomfortable if I approved & added a certain badge which was suddenly changed without my consent. 
2. Backward compatibility. These maintainers are now aware of the `polar` label and might add it manually in the future to get the badge. So we always need backward compatibility when making such a change. Our implementation should also make sure that we don't add our new badge when a legacy badge exists.

Given 2, I don't think we have to do a migration now and would be better of making one in the future if we want to clean things up.
