### ISSUE TITLE
Extension: Support backer use case

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1110]
### What
Backers can install our Chrome Extension. Offering the badge to show on all issues for seamless pledging across the board.

### Why
- Increase funding towards maintainers

### How

1. In case an issue is badged: Do nothing
2. Otherwise: Showcase the badge on the issue as if it was embedded
3. Custom design though to clarify that it's a inbound pledge, i.e different than one from the maintainer

### Prerequisites
https://github.com/polarsource/polar/issues/1109 Let's do this one first to ensure maintainers can seamlessly handle it to avoid any friction.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1110">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1110/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1110/pledge.svg">
</picture>
</a>

**Comment by emilwidlund** [comment]
Closing this as we're about to remove the Chrome extension all together.
