### ISSUE TITLE
Worker tasks should use a locally instantiated DB session maker

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1148]
Following the work done in #1140 and #1147, I've noticed that worker tasks currently use the global `AsyncSessionLocal` to open DB sessions.

While practical, it gives us less control about how/when the database engine is opened/closed. Besides, it makes it harder to implement unit tests; as it's difficult to swap the session with the fixture test session. The solution now is to monkey-patch  `AsyncSessionLocal` on a per-module basis, like I mention here:

https://github.com/polarsource/polar/blob/41b3210a97cd9d60e6121578708f289e10b6bfe5/server/tests/integrations/github/tasks/test_webhook.py#L37-L56

---

It would be a great improvement if we could store the DB engine instance and the associated session maker inside the `WorkerContext`, like we already do for the Redis instance. All we need is to add some logic to the startup/shutdown events of the worker to add those ones.

Then, in unit tests, it would be trivial to build a context with the test session and run the task with it.

---

Ultimately, my goal would be to get rid of those global `AsyncEngineLocal` and `AsyncSessionLocal` entirely.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1148">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1148/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1148/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Love it! That would be a super nice enhancement
