### ISSUE TITLE
Exceptions in workers are not logged

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1158]
Something is swallowing exceptions from worker tasks, and doesn't log them.

I've tried with a `raise Exception("what")` in the top of a worker, and nothing happens.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1158">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1158/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1158/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
My bad! I was a bit aggressive with my logging config override, which ended up in this situation. Fixed by #1159!

**Comment by zegl** [comment]
Nice!
