### ISSUE TITLE
Bug: Splitting UI Dark Mode Issues

### ISSUE THREAD

**Issue by JacobCoffee** [polarsource/polar#1191]
There are some light-theme elements in this, seems wrong?

Browser: Firefox
OS: Windows

![image](https://github.com/polarsource/polar/assets/45884264/da71340b-b9d8-4dbe-93ae-e2a0567818b2)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1191">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1191/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1191/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
This indeed looks a bit wrong, thanks for reporting the bug. I've opened a PR that improves the looks of this modal in dark mode. :)
