### ISSUE TITLE
Show issue description in our issue page

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1200]
<img width="865" alt="Screenshot 2023-09-18 at 15 43 17" src="https://github.com/polarsource/polar/assets/281715/c93a2916-fce2-452a-ad6c-bf44bd9e0b73">

Great for two purposes:
1. All context in one-place (better conversion)
2. Capture SEO with context of funding
3. Bonus: Looks nice and more professional

How it's supposed to work:
- Cutoff the description after X amount of words. So it's around the length of what is seen in the design
- Mimic the markdown formatting

However, the last part can become incredibly tricky and we should progressively enhance it over time. E.g code highlighting, todos etc. For starters I think we can begin with a whitelist of only a few support types of markdown and filter out everything else. Cutting up until we reach the first point of non-supported markdown, e.g code example.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1200">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1200/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1200/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Idea for the Markdown rendering problem: apparently, GitHub has an API for that: https://docs.github.com/en/rest/markdown/markdown?apiVersion=2022-11-28

Might be worth to check it out and see what's possible to do with it. If it works, we can cache the result on DB/Redis to save our token rate limits.

**Comment by birkjernstrom** [comment]
Oh wow that's awesome! Yes we should definitely leverage that to avoid reinventing the wheel + making it 1:1 with the source.

Yes, by using app installations for it upon issue updates/creation and overwriting a cache with no TTL - I don't think we'll ever get close of running into ratelimit issues (famous last words).

This made me excited ☺️
