### ISSUE TITLE
Implement updated design of issue page

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1201]
The left-hand side of this updated design:
<img width="865" alt="Screenshot 2023-09-18 at 15 43 17" src="https://github.com/polarsource/polar/assets/281715/cb0de75c-8c6c-46bb-afe9-a7f47af5b959">

This design reflects some features in the works & some added data that we can progressively enhance later.

**Todo**
- [ ] Design empty states, e.g no funding.

**First iteration**
- Issue title & meta data
- Funding & backer avatars
- Org & repo details

**Progressive enhancements (later)**
- #1125 
- https://github.com/polarsource/polar/issues/1200

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1201">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1201/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1201/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
We display the number of 👍 under the title:

<img width="500" alt="Capture d’écran 2023-09-20 à 10 52 25" src="https://github.com/polarsource/polar/assets/1144727/9b912024-3af3-4cc5-a952-58b276aa05af">

Is it:

* The number of 👍 *only*?
* The sum of *all reactions*?
* Or, should we show each reactions (👎, 🚀, 🎉...) separately?

**Comment by emilwidlund** [comment]
🥳
