### ISSUE TITLE
Issue row redesign in dashboard

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1202]
### What
Redesign how we showcase issues across Polar (dashboard/sites etc) to reflect some incoming and updated changes that all influence what & how we show Polar date related to issues.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1202">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1202/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1202/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Update https://github.com/polarsource/polar/issues/1228 once it's done

**Comment by emilwidlund** [comment]
Design & Figma link: https://www.figma.com/file/1p2oOjsRBgSrr3SC4zySJG/Polar-v0.3%3A-Rewards-%26-Social?type=design&node-id=288-1691&mode=design&t=FphuEgKnbb5OOyUW-0
