### ISSUE TITLE
Move API Token creation into the public /settings page for users

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1230]
Create API tokens in personal settings to use as Bearer tokens in our Public API vs. cookie.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1230">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1230/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1230/pledge.svg">
</picture>
</a>

<sub>[POL-41](https://linear.app/polar-sh/issue/POL-41)</sub>

**Comment by zegl** [comment]
Do you mean something like this? 😉 

https://polar.sh/settings/tokens

**Comment by zegl** [comment]
Test

**Comment by birkjernstrom** [comment]
Haha oops. Yes. Forgot about it since it's hidden.

Will update the description. Since we'll work on our API/SDK this upcoming quarter, I think we can quickly design and move this into our main settings (nice prompt for the API given our audience)

**Comment by birkjernstrom** [comment]
Awesome, this is chef kiss
