### ISSUE TITLE
[POL-22] Testing outside issue

### ISSUE THREAD

**Issue by birkjerntest** [polarsource/polar#1248]
Footer

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1248">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1248/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1248/pledge.svg">
</picture>
</a>

<sub>[POL-22](https://linear.app/polar-sh/issue/POL-22)</sub>

**Comment by frankie567** [comment]
Comment from GitHub to Linear ?
