### ISSUE TITLE
Leverage FastAPI/Pydantic features to avoid the `from_db` pattern

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1250]
## Context 

Across the codebase, we adopted a pattern where we implement dedicated classmethod `from_db` to build a Pydantic object from an SQLAlchemy one. For example:

https://github.com/polarsource/polar/blob/844c1add10e4b0b887a8ae90152691bf8de2cd4d/server/polar/organization/schemas.py#L34-L50

And then:

https://github.com/polarsource/polar/blob/844c1add10e4b0b887a8ae90152691bf8de2cd4d/server/polar/organization/endpoints.py#L102-L105

While working well, it's a bit verbose and we miss the purpose of Pydantic which is precisely to take *input data in any form* and transform it to a valid object compliant with our schema. Basically, we're doing by hand what Pydantic can make automatically.

## Proposal

If we consider the example above, the same behavior could by achieved like this:

```py
# polar/kit/schemas.py

class Schema(BaseModel):
    class Config:
        orm_mode = True  # Enable Pydantic to work with arbitrary ORM objects, like SQLAlchemy
        json_dumps = json.dumps
        json_loads = json.loads
        json_encoders = {SecretStr: lambda v: v.get_secret_value() if v else None}
```

```py
# polar/organization/schemas.py

class Organization(Schema):
    id: UUID
    platform: Platforms
    name: str
    avatar_url: str

    bio: str | None
    pretty_name: str | None
    company: str | None
    blog: str | None
    location: str | None
    email: str | None
    twitter_username: str | None

    pledge_minimum_amount: int
    pledge_badge_show_amount: bool
```

```py
# polar/organization/endpoints.py

@router.get(
    "/organizations/lookup",
    response_model=OrganizationSchema,
    tags=[Tags.PUBLIC],
    description="Lookup organization. Like search but returns at only one organization.",  # noqa: E501
    summary="Lookup organization (Public API)",
    status_code=200,
    responses={404: {}},
)
async def lookup(
    platform: Platforms | None = None,
    organization_name: str | None = None,
    session: AsyncSession = Depends(get_db_session),
) -> Organization:
    # Search by platform and organization name.
    # Currently the only way to search
    if platform and organization_name:
        org = await organization.get_by_name(session, platform, organization_name)
        if org:
            return org

    raise HTTPException(
        status_code=404,
        detail="Organization not found ",
    )
```

The key thing here is that we can directly return the SQLAlchemy object from our endpoint. Thanks to `response_model`, FastAPI will automatically feed it to Pydantic that will make the conversion.

Of course, this is a simple case where the schema exactly maps the field of SQLAlchemy. For more advanced cases where we change the name of a field, or if we build slightly different schemas, we can leverage Pydantic features like aliases or validators.

The only drawback with this approach is that it's possible that we may trigger `ValidationError` while generating our API response, if we have a mismatch between our schema and the underlying data. It's true but that's something that should be considered a bug and verified by unit tests.

---

All in all, I think it could be a good improvement of the code base, that would be more idiomatic regarding FastAPI and Pydantic patterns.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1250">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1250/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1250/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
Saying that this pattern "defeats the purpose of Pydantic" is a bit harsh. More like, we're not always utilising Pydantic in the best possible way. :)

We do use the pattern that you've suggested above in a few places, but have slowly moved away from it more and more, and I might be the one to blame there for a lack of understanding of how we can use Pydantic. But on the other hand, it's just a mapper, nothing complicated, and in this way we do get static type analysis, so there are some pros to it as well. :)

With Pydantics capabilities, it feels like it starts easy, until it suddenly isn't, where you need to have some fallback or want to have some extra logic before creating the response object. For example in this scenario, can you do this in Pydantic, and in a way that feels intuitive and as easy to read as this is? What would it look like?

https://github.com/polarsource/polar/blob/844c1add10e4b0b887a8ae90152691bf8de2cd4d/server/polar/pledge/schemas.py#L156-L172

By scanning our codebase, it seems to be around 50/50 between mappers that are as simple as the one you linked above and mappers like the one for pledges that have some sort of custom logic in it.

**Comment by frankie567** [comment]
> Saying that this pattern "defeats the purpose of Pydantic" is a bit harsh. More like, we're not always utilising Pydantic in the best possible way. :)

Sorry if it felt that way, my intention is never to put blame on anyone's work. Just wanted to open up the discussion. I've edited the issue title :)

---

> With Pydantics capabilities, it feels like it starts easy, until it suddenly isn't, where you need to have some fallback or want to have some extra logic before creating the response object. For example in this scenario, can you do this in Pydantic, and in a way that feels intuitive and as easy to read as this is? What would it look like?

For those cases, we could have `@property` on the SQLAlchemy objects. Pseudo-code:

```py
from dataclasses import dataclass

from pydantic import BaseModel


@dataclass
class User:
    name: str


@dataclass
class Organization:
    display_name: str

    @property
    def name(self) -> str:
        return self.display_name


@dataclass
class Pledge:
    id: int
    user: User | None
    organization: Organization | None

    @property
    def pledger(self) -> User | Organization:
        if self.organization is not None:
            return self.organization
        elif self.user is not None:
            return self.user
        raise Exception("Meh")


class Pledger(BaseModel):
    name: str

    class Config:
        orm_mode = True


class PledgeSchema(BaseModel):
    id: int
    pledger: Pledger

    class Config:
        orm_mode = True


u = User(name="Foo")
o = Organization(display_name="Orga")
p_u = Pledge(id=1, user=u, organization=None)
p_o = Pledge(id=2, user=None, organization=o)

p_u_s = PledgeSchema.from_orm(p_u)
p_o_s = PledgeSchema.from_orm(p_o)

print(p_u_s)
print(p_o_s)
```

This case is indeed a bit tricky 🙃
