### ISSUE TITLE
Backoffice: send daily reminders to Discord

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1265]
Create a daily reminder job to notify us in Discord about pending payouts and disputes, to make sure that we're handling them.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1265">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1265/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1265/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Cleaning up our GitHub issues and closing stale issues unless they're related to current focus. They'll resurface if needed.

We have this in the form of Discord notifications upon issue completed. Sufficient for now.
