### ISSUE TITLE
🎯 🎉 Issue Promotion

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1292]
# 👀 What

We should reactivate maintainers by reminding them to badge issues on their repositories, in particular the popular ones amongst the community.

# 👥 Who

Maintainer

# 🚢 How

******************Must have******************

- [ ] ~~#1304~~
- [x] #1368 

**Should have**

- [ ]  #1305
- [ ]  #1306

**Could have**

- [ ]  #1307

# 📓 Decision log

**What’s the communication channel?**

An email sent to the maintainer.

**What should be its frequency?**

It depends on the maintainer activity. If they recently badged issues (< 1 month — configurable as env var), they don't receive an e-mail. Otherwise, they receive this email weekly.

**What issues should we highlight?**

We should highlight issues that are **unbadged** and sort them by creation date (descending), number of positive reactions and comments (descending).

It avoids us to come up with complex and arbitrary rules, and works out-of-the-box no matter the popularity of the repo.

Let's take the 5 first (let's make this an environment variable so it's easy to tune).  

**Do we add marketing material in it?**

I think the message would be more impactful if we refer to success stories we had with other maintainers.

**Comment by frankie567** [comment]
We've implemented Loops to trigger marketing email sequences to onboard maintainers.

The original email reactivation idea is yet to be implemented, but we decided to unprioritize it for the moment. Pushing this to the backlog.

**Comment by birkjernstrom** [comment]
Cleaning up GitHub. Closing older ideas - will resurface if needed or feedback given instead.
