### ISSUE TITLE
Add a notification setting to disable the weekly reminder

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1305]
It should be possible to opt-out the weekly reminder in the notification settings.

Design needed for clear wording.

**Comment by emilwidlund** [comment]
@frankie567 Just wrapped up a design for this. See: https://www.figma.com/file/1p2oOjsRBgSrr3SC4zySJG/Polar-v0.3%3A-Rewards-%26-Social?type=design&node-id=611-15490&mode=design&t=FphuEgKnbb5OOyUW-11

**Comment by frankie567** [comment]
Thank you for this, @emilwidlund 🙏 It looks great!

It does a bit more than we'll implement on a first intent but I like it being future-proof!

**Comment by emilwidlund** [comment]
@frankie567 Yes! Added some more sections for future expansion :)
