### ISSUE TITLE
Create an empty state for issues

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1326]
Currently, it's a blank screen for repositories without any issues whatsoever. Would be nice to have an empty state here, i.e inbox zero. Even more so to link to creating a campaign instead in those rare cases when a maintainer has no issues :)

**Comment by frankie567** [comment]
I think it has been done 😄

<img width="1840" alt="Capture d’écran 2023-10-18 à 16 19 54" src="https://github.com/polarsource/polar/assets/1144727/814fcf92-b310-47dd-b5e1-7ce620eb9d0b">

**Comment by emilwidlund** [comment]
Ah yes! Thanks for closing 💪
