### ISSUE TITLE
Funding page: Enhance the funding stats

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1331]
<img width="519" alt="image" src="https://github.com/polarsource/polar/assets/281715/5b55c5a9-e062-42db-a222-9947f584c393">

Improve the funding section of our funding page for issues, e.g [this page](https://polar.sh/polarsource/polar/issues/900), and what is shown in the screenshot as "$0 pledged"

**Improvements**
- [x] Empty state: Remove the section if there is no funding to show vs. showing "$0 pledged"
- [x] Change term from "pledges" to "funding"

**Comment by AniswagMC** [comment]
Hey, I'd like to try my hand at this issue, if it isn't already solved, I'd love for you to assign it to me.

**Comment by zegl** [comment]
@AniswagMC Done!

**Comment by zegl** [comment]
As I haven't heard anything from you @AniswagMC since this was assigned to you, I'll now unassign it.
