### ISSUE TITLE
Polar SDK: Replace Axios with standard Fetch library

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#1341]
Replace the Axios client in the current API client with the standard Fetch library.

**Comment by frankie567** [comment]
@zegl and I had that in mind for a while 😄

The difficulty right now is that our OpenAPI client generator (https://github.com/ferdikoomen/openapi-typescript-codegen) can indeed use `fetch`, but it doesn't expose an API to manage [Next.js cache options](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#caching-data) (+ [Vercel Data Cache on CDN](https://vercel.com/docs/infrastructure/data-cache)).

So, if we do it like this, we'll likely have issues with things that get cached forever without any possibility to refresh.

The solution we envisioned were:

* Fork our client generator and tweak it to include the caching options in every methods
    * ✅ We wouldn't have to change our calls in the frontend
    * ❌ Maintenance burden of this custom version
* Change our client generator. We noted the following ones (we need to ensure it supports setting fetch cache options):
    * https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/typescript-fetch.md 
    * https://openapi-ts.pages.dev/openapi-fetch/
    * ✅ Nothing to support ourselves
    * ❌ We have to change our calls everywhere in the frontend

**Comment by emilwidlund** [comment]
@frankie567 Thanks for the nice write-up! Good food for thought. This is something we could put aside for now and pickup once we've decided on a path forward as it's a nice-to-have 👍

**Comment by zegl** [comment]
@frankie567 @emilwidlund I did some quick testing a while back with `openapi-generator`, and I don't think that the rewrite of our code will be _that bad_. The generator has lots of options and with some tweaking we can get it to generate code that's very similar to the current one.
