### ISSUE TITLE
Lower dispute window to 7 days

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1353]
Currently, our dispute window is 14 days which is a bit.... much. Let's lower it to 7 and marry the invoice due date for funding on completion to match.

**Todo**
- [x] Set invoice due date to 7 days https://github.com/polarsource/polar/pull/1344
- [ ] Change dispute window in copy (FAQ and elsewhere) to be 7 days moving forward

**Comment by zegl** [comment]
Invoice due date was fixed by #1344
