### ISSUE TITLE
Agree on a pagination strategy for the Public API

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1357]
## 👀 What?

We currently have the `ListResource` schema in place to handle paginated resources. However, there is currently no parameter to control this pagination, we always return the entire list of objects.

We should agree on a strategy so we have a common way to paginate resources across the Public API

## 📓 Decision log

**What parameters should we expose?**

Different flavors can be seen in the wild; personally, I like the `limit` (number of items on a page) and `skip` (where to start from) pattern. It mirrors the way SQL DB works for paginating.

For example, here is how we can get the page 3 when having 10 items per page: `https://api.polar.sh/api/v1/resources/?limit=10&skip=20`

**What is the default and max size of a page?**

We should have a good balance between usability and resource-saving. Personally, I would recommend a default of **10 or 20 items** and a hard limit of **100 items**.

**Comment by birkjernstrom** [comment]
I think this is great and agree with the proposal. I know cursors are popular too and there are a lot of pros with them, but I do find that the limit/skip pattern is more intuitive, readable and predictable.

**Comment by frankie567** [comment]
@birkjernstrom @zegl If we all agree here, I would like to move forward on this. I'll need this to fix #1374 properly.

**Comment by zegl** [comment]
@frankie567 Yes, I think that `limit`/`skip` or `limit`/`page` as query parameters makes sense. It doesn't really matter which one tbh, _page_ might be more intuitive for the user as it's easier to loop (`for page in range(0, 10): ...`) than keeping track of the offset.

You can pick which one!

**Comment by birkjernstrom** [comment]
+1. Fully supportive of this effort, nice to get in-place and completely
trust your judgement Francois re: choice between limit/page limit/skip

**Comment by frankie567** [comment]
I've implemented the tooling for this! There'll still be an ongoing effort to integrate it to existing endpoints but we at least have common tools for this. A few highlights!

## The `polar.kit.pagination` module

Everything related to pagination is now in `polar.kit.pagination`, including `ListResource` and `Pagination` schemas that I moved here.

## `PaginationParams` and `PaginationParamsQuery` dependency

`PaginationParams` is a named tuple with two values: `page` and `limit`. This structure stores the values passed by the user in the API.

A FastAPI dependency is implemented to retrieve them easily from an API endpoint, with proper OpenAPI documentation, defaults (page 1 and limit 10) and validation. It's worth to note that `limit` has a hard limit set by the env var `API_PAGINATION_MAX_LIMIT`, which defaults to 100 currently.

To use this dependency in an endpoint, we just need to add it in parameter with the `PaginationParamsQuery` annotation:

```py
@router.get("/list")
async def get_paginated_list(pagination: PaginationParamsQuery):
    print(pagination.page, pagination.limit)
```

## Paginate items

How we actually paginate items is left to the service implementation.

However, to handle common cases, I've added a `paginate` function which takes a SQLAlchemy statement and pagination params. It's capable of limit/offset the query and return us the total count in one query. For example:

```py
statement = select(Resource).where(Resource.user_id == user.id)
items, total_count = await paginate(session, statement, pagination=pagination)
```

## Build `
ListResource` schema

When we're ready to return the API data, we can build a `ListResource` + `Pagination` schema. I've added a class method helper to build it:

```py
return ListResource.from_paginated_results(items, total_count, pagination_params)
```

where `pagination_params` is the original `limit`/`page` named tuple. It's used to return the maximum page number to the user.

**Comment by birkjernstrom** [comment]
This is really nice! Love the design choices here of the API this offers internally for implementation. Great work on this @frankie567 – it's awesome to have in-place.
