### ISSUE TITLE
Investigate timeouts in Vercel

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1374]
Vercel rolled out a change where the Serverless functions now have a default timeout of 15 seconds (*TIL that Vercel runs everything as a serverless functions*).

@birkjernstrom investigated and noticed some timeouts:

> I checked and it seems like we're having a bit of timeouts as a result
> <img width="951" alt="untitled" src="https://github.com/polarsource/polar/assets/1144727/49886ce5-14c1-4493-9415-c5baf5f51503">

---

I looked in Sentry and it seems that we indeed have some pages that are quite heavy to generate:

<img width="1464" alt="Capture d’écran 2023-10-06 à 09 08 52" src="https://github.com/polarsource/polar/assets/1144727/77b525be-51aa-4930-8598-5398c0c065a8">

It looks like there are two main pages that are taking lot of time:

* The updated maintainer's public page: the current implementation loads every issues, which is not very good (my fault). I think we should solve this by going forward with #1357.
* ~~The maintainer `/issues` page. I don't really understand why since the issues are loaded client-side directly from the API, but it's true that the initial load is quite long. Worth to have a look.~~ (nope)
* The issue page. It can be long on first load since we query GitHub to render the Markdown.

**Comment by zegl** [comment]
Our maximum execution seems to be 1 minute [example](https://vercel.com/polar-sh/polar/5QwxzaeAcoCR84zTTkBkLmEcxzgd/functions?name=%5Borganization%5D.rsc). But I can't figure out where this configuration comes from.

**Comment by frankie567** [comment]
We haven't seen timeouts for a few days now, I think we are okay regarding this.
