### ISSUE TITLE
Don't check soft deleted accounts on account create validation

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#1407]
Currently, in case an account (Stripe or Open Collective) is soft deleted, it's not shown in the finance tab and the maintainer is then promoted to setup an account (good). However, in the modal to connect a Stripe or OC account, they get an error message that an account is already connected to the organization, i.e our validation logic here does not filter out soft deleted accounts.

**Comment by frankie567** [comment]
Won't fix for now 😄

Soft-deleting an account is not possible from the API right now (the change was done manually in DB). Since we have some unique constraints on account (good), the only way we could handle this would actually be to hard-delete the entry.
