### ISSUE TITLE
User settings are only accessible from the Backer profile

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1430]
Currently, the settings menu is only accessible when the Backer profile is selected:

<img width="1840" alt="Capture d’écran 2023-10-12 à 08 52 15" src="https://github.com/polarsource/polar/assets/1144727/31de2264-0537-48d3-8b03-804e3b473cd6">

<img width="1840" alt="Capture d’écran 2023-10-12 à 08 54 27" src="https://github.com/polarsource/polar/assets/1144727/775fada8-2fdd-4af0-8bc4-a98fec872f84">

Since those settings are common to the whole user account, it might make sense to make it accessible more globally. For example, it might live in the dropdown above *Log out*.

**Comment by emilwidlund** [comment]
This has been resolved now when Maintainer & Backer navs are on the same page.
