### ISSUE TITLE
Could we get rid of Poppins webfont?

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1466]
Currently, we're loading Poppins WebFont everywhere in our app:

https://github.com/polarsource/polar/blob/df8e556a667a38243c838e93576e056e16bbb83d/clients/apps/web/src/app/layout.tsx#L55-L58

We use it in a Tailwind family called `display`:

https://github.com/polarsource/polar/blob/df8e556a667a38243c838e93576e056e16bbb83d/clients/apps/web/tailwind.config.js#L69-L72

---

Loading this font adds quite some overhead (P95 ~800 ms) if I believe Sentry performance monitoring: https://polar-sh.sentry.io/performance/summary/spans/resource.link:991e8284ee56a0ad/?project=4505047079976960&query=&statsPeriod=14d&transaction=%2Fencode

However, we use it very rarely: only at three places in the project: https://github.com/search?q=repo%3Apolarsource%2Fpolar+%22font-display%22+path%3A%2F%5Eclients%5C%2F%2F&type=code

Thus, I think we could safely remove it and save an external resource loading.

**Comment by emilwidlund** [comment]
Yep, I agree with this. Going with Inter as the exclusive font on the platform is fine. Let's do it.
