### ISSUE TITLE
Subscriptions success page design and copy

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1480]
We should have a nice page to redirect the user afer they successfully subscribed to a tier.

A few comments:

* We have access to the backer name, email and the subscription tier they subscribed to
* If they are new user to Polar, an account is automatically created for them and they can now login using a magic link. We have a similar upsell for pledges:

<img width="1840" alt="Capture d’écran 2023-10-17 à 11 08 44" src="https://github.com/polarsource/polar/assets/1144727/1c34a6a6-bec1-4254-86c3-65fa48948da7">

* Authenticated user should not see this upsell. What should we show, do for them?

**Comment by emilwidlund** [comment]
Good idea - I can take a stab at that!
