### ISSUE TITLE
Accounts can't be setup both for Backer Rewards and Personal Organization profile

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1512]
Related to #1407 and to the problems @aeworxet encountered (Discord: https://discord.com/channels/1078611507115470849/1151973214562558085/1164488962363117599)

---

Accounts were designed for maintainer's organization. As such, `organization_id` is mandatory and it has a unique constraint on it.

Since Rewards, backers can also now configure an Account. We added `user_id` column for this.

However, it causes issues if the user already configured an account for their personal organization (as maintainer): indeed, because of the `organization_id` unique constraint, we can't create another account for the same one. The Rewards panel don't detect it since `user_id` is not set.

We should probably make `organization_id` optional and drop the unique constraint.

## Sub-problem

`Account` are not deleted when the organization is uninstalled. We should probably remove them also.

**Comment by zegl** [comment]
As a side note: A nullable and unique column in PostgreSQL can have many rows where the column is NULL, this is because null is not comparable to null.
