### ISSUE TITLE
Devcontainers/Codespaces: automate GitHub App creation

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#1676]
Continuing on #1236 and #1671.

The server requires a valid GitHub App configuration to even boot.

We should try to automate this as much as possible (or maybe get rid of it)?

GitHub does provide a way for the user to add Codespace secrets via via https://github.com/settings/codespaces

**Comment by frankie567** [comment]
Maybe we could leverage the App Manifest flow for this: https://docs.github.com/en/apps/sharing-github-apps/registering-a-github-app-from-a-manifest

Basically, we build a URL containing the manifest for our GitHub app. We should redirect the user to this URL, and after they submit the app creation, they are redirected back to another URL with a temporary code (similar to OAuth2). At that point, we could retrieve the app's secret and set it in `.env`.

**Comment by zegl** [comment]
@frankie567 That's really cool, I didn't know that App Manifests existed 🤯 Thanks for sharing!

**Comment by zegl** [comment]
Fixed by #1701 and #1678
