### ISSUE TITLE
User is able to have multiple subscriptions on the same org/repo

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#1714]
Allowing users to subscribe multiple times to different tiers on the same org/repo doesn't make sense in a Subscription model.

We should:

- [x] Implement checks on the server to see if a user already has a subscription on an org/repo. If someone tries to subscribe to an additional tier, we should remove the first one (acting like an upgrade or downgrade).
- [ ] Update the buttons on Subscription cards to show Subscribe/Manage depending if a subscription is found or not.

**Comment by frankie567** [comment]
I've implemented a new endpoint to upgrade/downgrade an existing subscription: https://api.polar.sh/docs#/subscriptions/subscriptions%3Aupgrade_subscription

All it requires is to pass a valid `subscription_tier_id` belonging to the same organization/repository. We do not need to go through Stripe, all happens in the background. Stripe will automatically prorate the price in the next invoice.

May I let you handle the UI's side, @emilwidlund? I think it requires two things:

* From the maintainer's page, we should show an *Upgrade* button on the other tiers calling this endpoint, and show a success message.
* From the settings page, we could simply redirect to the right maintainer's page subscription tab, so the user could go through the same path as above.

---

There is also a check now on `/subscribe-sessions/create` to prevent user to subscribe twice to the same organization/repository.
