### ISSUE TITLE
Killswitch for all feature-flags in Settings

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#1803]
As a Polar employee, its hard to get the "proper" Polar experience which is served to all our users, because of all feature flags that by default are served to all employees.

I suggest that we implement a "killswitch" in Settings, where you can opt-out of certain feature flags without having to go to Posthog and adjust the roll-out target audience.

**Comment by zegl** [comment]
This sounds like a good opportunity to use the Posthog Toolbar https://posthog.com/docs/toolbar
