### ISSUE TITLE
I could not found my reword page

### ISSUE THREAD

**Issue by Emiyaaaaa** [polarsource/polar#1837]
I am a maintainer of type-fest, and I resolved 2 issues that funding in polar, total about $120,
But now I could not found my reword page.
Need some help, thanks~
![image](https://github.com/polarsource/polar/assets/37606228/f7833f58-42f8-4627-b11f-fdc0a1a8355c)

**Comment by emilwidlund** [comment]
Hey @Emiyaaaaa - this is a known bug for accounts that haven’t connected with GitHub yet. I’ll fix it first thing Monday morning. 

I believe however that you can access the page by going directly to https://polar.sh/rewards - or simply just connect your GitHub repositories by clicking the link in the bottom left corner.
