### ISSUE TITLE
Enhancement: Count other positive emoji as 👍🏽 

### ISSUE THREAD

**Issue by JacobCoffee** [polarsource/polar#1909]
If I understand correctly this:

<img width="134" alt="image" src="https://github.com/polarsource/polar/assets/45884264/e4983c2d-5fe9-4f85-9f10-2fd40cbd90a3">

Only checks against an open issues 👍🏽 count.

But it would be nice to capture other positive emojis so we get a more holistic view:

<img width="278" alt="image" src="https://github.com/polarsource/polar/assets/45884264/631fb3f0-081a-461c-92de-68be12ffe47c">

I don't think those would need to be extra emojis, rather just +1'd to the 👍🏽 on the Polar dashboard

**Comment by JacobCoffee** [comment]
If I do not understand correctly.. well.. just ignore me 😝

**Comment by zegl** [comment]
Hey @JacobCoffee! You are understanding it correctly. :-)

While we are counting all "positive" reactions (thumbs up, rocket, hearts, etc) for sorting purposes, it doesn't seem like we're using that that counter in the views. 

I'll get this fixed as soon as I can.
