### ISSUE TITLE
Attempting to connect a GitHub account which already is linked with another account results in a vague error

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#1914]
### What

If you attempt to connect a GitHub account which already is linked with another account, you'll get a vague error which hints at an issue with the access token. We should handle this better.

<img width="621" alt="image" src="https://github.com/polarsource/polar/assets/10053249/ff58f038-6925-451f-825e-b2c0f511d77c">

### Proposal

We should hint to the user that the account already is linked to someone else.

**Comment by frankie567** [comment]
Will be fixed by #1977! Actually, proper error message was there, but some nasty React re-rendering were submitting the callback twice, so you got the expired/invalid error after (very briefly) seeing the already-linked error.
