### ISSUE TITLE
Emojis and special characters are not rendered correctly in emails

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1954]
Probably an encoding issue when we set the email body.

<img width="808" alt="Capture d’écran 2023-12-13 à 08 46 54" src="https://github.com/polarsource/polar/assets/1144727/0cb253d7-ebf5-4b33-a320-d1696a0ccc0d">

<img width="694" alt="Capture d’écran 2023-12-13 à 08 47 05" src="https://github.com/polarsource/polar/assets/1144727/f8e89511-074f-4b45-b441-1db5cba7bf1d">

**Comment by zegl** [comment]
Nice find! I'll fix it!
