### ISSUE TITLE
Ability to query Subscription statistics for multiple tier types

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#1966]
With the addition of a free tier, I would like to have the ability to use `getSubscriptionsStatistics` with an array of tier types, instead of a single tier type which is supported today. 

This would allow us to build a graph of overall subscription statistics, but also a graph of "paid" subscription statistics.

**Comment by emilwidlund** [comment]
@frankie567 Let me know your thoughts on this :)

**Comment by emilwidlund** [comment]
<img width="655" alt="image" src="https://github.com/polarsource/polar/assets/10053249/fe6e7f8d-e7f2-4405-8bf8-7f049c31d6c2">

To clarify: I want to build a graph like this, but excluding the free tier data :)

**Comment by frankie567** [comment]
Should be doable! Let's go 👨‍🍳

**Comment by frankie567** [comment]
@emilwidlund I've tweaked the API accordingly!

I didn't touch the Dashboard UI (apart from making it work with the new query parameter), so I'll let you tweak the graphs and content as you wish 😄

**Comment by emilwidlund** [comment]
@frankie567 Thanks! :)
