### ISSUE TITLE
Re-enable reactions and funding goal in OG images

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#2038]
See #2037

**Comment by b4s36t4** [comment]
Hi @zegl would love to work on this. This is just a revert of the pr you mentioned in description or would there be extra changes needed?

**Comment by zegl** [comment]
Hey @b4s36t4. Unfortunately not, something is broken in the renderer at the moment, and it can be quite tricky to debug. I'd recommend against trying to work on this one.

**Comment by frankie567** [comment]
Closing as we probably won't dedicate time for this, lot of other focuses right now 😄
