### ISSUE TITLE
Links lead to 404 when trailing slash is missing 

### ISSUE THREAD

**Issue by francorbacho** [polarsource/polar#2042]
Visiting [`https://docs.polar.sh/faq`](https://docs.polar.sh/faq) instead of [`https://docs.polar.sh/faq/`](https://docs.polar.sh/faq/) makes links lead to 404. Lots of pages (like the Contribute submenu on issues) link to the `/faq`.

**Comment by zegl** [comment]
Thanks for the bug report @francorbacho! I've now updated our links to the FAQ.
