### ISSUE TITLE
Subscribers count includes cancelled subscriptions

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#2078]
Doh!

<img width="415" alt="Capture d’écran 2024-01-03 à 15 34 15" src="https://github.com/polarsource/polar/assets/1144727/cfb4384a-98f3-47f5-b1f4-414dedf18cb8">
<img width="743" alt="Capture d’écran 2024-01-03 à 15 34 18" src="https://github.com/polarsource/polar/assets/1144727/2df19f06-2d85-406a-b964-7ceaa165d187">

**Comment by emilwidlund** [comment]
@frankie567 Why are there multiple cancelled subscriptions from me?

**Comment by frankie567** [comment]
Didn't you unsubscribe/resubscribe on the Free plan?
