### ISSUE TITLE
Subscription Tier: hidden under toolbar after navigation

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#2096]
https://github.com/polarsource/polar/assets/47952/b111219f-a6a9-4b64-ae91-9f577af9fd17

**Comment by sourabpramanik** [comment]
Can someone assign me this issue? I would like to work it

**Comment by zegl** [comment]
@sourabpramanik Hey! Feel free to work on it and send a PR, as far as I know no-one is working on this right now.

**Comment by sourabpramanik** [comment]
Thanks @zegl 👍
