### ISSUE TITLE
Subscriptions: tier group icon is missing when creating new tier

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#2098]
<img width="462" alt="Screenshot 2024-01-04 at 13 29 18" src="https://github.com/polarsource/polar/assets/47952/ff2aecb6-2711-4350-8d74-df68653f007d">

**Comment by emilwidlund** [comment]
Can't reproduce in production nor locally.

**Comment by zegl** [comment]
My bad, it started to work after I restarted the web server.
