### ISSUE TITLE
"Add badge to issues" section doesn't count open issues correctly

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#2166]
As reported on Discord: https://discord.com/channels/1078611507115470849/1109142435981967360/1194223555282468934

---

It looks like we do Issues + PR

**Comment by zegl** [comment]
Yeah, the number in the list view is the number that comes from GitHub, where PRs are also counted as issues.

That number has (historically) been used there as this component is used both during initial synchronisation and for settings. And for synchronisation this number is available very early, and enables us to say "Syncing n/N issues" before we know how many _real issues_ there actually are.

This inconsistency is probably Polars oldest bug :D
