### ISSUE TITLE
404 page requires JS

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#2172]
I think it would be a good idea to at a minimum render _something_ on 404 pages if JS is disabled.

**Comment by appills** [comment]
I think it would be a good idea to slap a <noscript> tag on every page if javascript is disabled

**Comment by zegl** [comment]
> I think it would be a good idea to slap a tag on every page if javascript is disabled

Most pages work decently without JS, I would want the 404 state to render without JS too.

**Comment by sourabpramanik** [comment]
Is anybody working on this issue? I would like to work on it.

**Comment by zegl** [comment]
@sourabpramanik Not that I’m aware of. Please do, PRs welcome!

**Comment by sourabpramanik** [comment]
Alright thanks 👍

**Comment by webbdays** [comment]
Hi,
should we go for plain 404 page for all.
or should we check if the browser supports JS.
I think we can use
noscript tag.

**Comment by frankie567** [comment]
FWIW, it seems that even the default 404 page does not work without JS. Next.js seems to always pick it up to inject its scripts.
