### ISSUE TITLE
Support dark mode without JS

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#2186]
If you disable JS, the theme is always the light one

**Comment by isaacharrisholt** [comment]
Having experimented with something like this before, it's technically _possible_ to toggle dark mode without JS. However, it's not really worth it. The setting won't persist across pages even if you do toggle it, so the only real option is to use the user's media preference.

The way Polar uses Tailwind makes this especially difficult by requiring a `dark` class to be added to a DOM element, as you can't really manipulate the DOM without client-side JS. You could potentially do this during SSR using the [Sec-CH-Prefers-Color-Scheme header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-CH-Prefers-Color-Scheme), but browser compatibility is currently poor.

My usual angle of attack here is to default to dark mode so as not to flashbang people, especially when the audience is devs 😅
