### ISSUE TITLE
Feat: Proposing issue and PR template

### ISSUE THREAD

**Issue by sourabpramanik** [polarsource/polar#2211]
It will be better if we have issues and PR templates for every repo in polarsource

**Comment by zegl** [comment]
Hey @sourabpramanik. I don't think that issue/PR-templates would currently solve a problem that we're currently facing.

Most of our issues and PRs are of high quality already, and I don't think that they would benefit of having an additional process.

I'll close this for now, but we might have to re-visit it at some point if low-quality issues becomes an issue.
