### ISSUE TITLE
Polar Fails to Load with Cookies Disabled

### ISSUE THREAD

**Issue by eusonlito** [polarsource/polar#2256]
I've encountered an issue where the website fails to load when cookies are disabled. This poses two major concerns:

* Privacy Protection: Many users disable cookies for privacy reasons. The site should support these privacy choices by remaining functional without cookies.
* SEO Impact: Search engine spiders and crawlers often access websites with cookies disabled. The current issue could negatively impact the site's search engine indexing and ranking.

Addressing this will improve user privacy support and ensure better SEO.

Regards!

![image](https://github.com/polarsource/polar/assets/644551/157055dd-9f06-41b6-abb8-f609ab79f4cf)

**Comment by zegl** [comment]
Hey @eusonlito! Thanks for the bug report, to help investigating this, could you please share which browser that you're using, and how you've configured it to disable cookies? It looks like you're using Firefox, or are you using a fork? Are you using any extension to disable cookies?

Thanks.

**Comment by eusonlito** [comment]
Hi @zegl! My first visit attempt has been on a mobile browser (Brave) where I browse without cookies by default (I only enable them on some sites where I need authentication).

For this issue I simply sent the screenshot from desktop firefox with cookies disabled (I use the extension https://addons.mozilla.org/es/firefox/addon/mcookies-disable/).

**Comment by eusonlito** [comment]
Access to storage (and cookies) should always be done through a simple wapper that takes these situations into account. It is easy to implement and the rest of the application forgets to control access related issues.

For example, here a very simple storage wrapper for one of my projects https://github.com/eusonlito/GPS-Tracker/blob/master/resources/views/assets/js/local-storage.js

:)
