### ISSUE TITLE
Bug: Creating a newline before a word makes the editor jump

### ISSUE THREAD

**Issue by isaacharrisholt** [polarsource/polar#2334]
Entering a newline just before a character in the post creator causes the editor to jump down and place the newline at the top of the screen.

See the video [here](https://github.com/polarsource/polar/assets/47423046/62f3c1b5-7b0d-4f77-92da-5ab70e7f3877).

**Comment by zegl** [comment]
Huh, that's _interesting_. Thanks for sharing the video, it makes it very easy to reproduce! 🙏
