### ISSUE TITLE
Settings: GitHub email is shown instead of username

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#2372]
I think that it would make more sense to show the GitHub username here instead of the connected primary email. Thoughts?

<img width="1400" alt="Screenshot 2024-01-30 at 14 03 00" src="https://github.com/polarsource/polar/assets/47952/5cb6aca9-4a43-4f32-a07a-1d2b007d85e0">

**Comment by frankie567** [comment]
Agree! But we would likely need to store the username on the `OAuthAccount` model _*_ (a bit reluctant to "trust" the `User.username`).

_*It would actually help me with the GH repository benefit_

**Comment by zegl** [comment]
Yes, agreed! We should have more data in the `OAuthAccount`. I think it would be cool if we could get rid of the `User.username` somehow.
