### ISSUE TITLE
Make `Preview` more accessible in the editor for long posts

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2430]
Long posts requires scrolling up to the top to preview. Easier to open in a separate tab & refresh to keep focus in the editor.

Ideas:
- Make topbar fixed to always follow along
- Keyboard shortcut to preview

Thank you @eval for the great feedback ♥️🙏🏼

**Comment by emilwidlund** [comment]
https://github.com/polarsource/polar/pull/2447 adds a `CMD + P` shortcut for preview.
