### ISSUE TITLE
Bug: Double scrollbars in editor

### ISSUE THREAD

**Issue by isaacharrisholt** [polarsource/polar#2435]
See [this](https://www.loom.com/share/aacc9f5151d24fc1ac84d6954db94295?sid=81236ff5-512e-46c4-b0b2-3a8c06a9d689) video.

The second scrollbar seems to appear when you switch between editor tabs. It persists across a page refresh, but disappears if you resize the window.

**Comment by birkjernstrom** [comment]
Thanks for reporting this @isaacharrisholt !  Just to confirm: Looks like you're on Windows?

**Comment by isaacharrisholt** [comment]
> Thanks for reporting this @isaacharrisholt !  Just to confirm: Looks like you're on Windows? 

Yep!
