### ISSUE TITLE
Bug: Left navigation in maintainer view leads to "undefined"

### ISSUE THREAD

**Issue by turbolent** [polarsource/polar#2454]
## Broken behaviour

When in maintainer view, using the navigation is broken

## Steps to reproduce

1. Go to https://polar.sh/maintainer
2. Click on username in left navigation, it expands
3. Click on username again

See 
- "Something went wrong!"
- URL is https://polar.sh/maintainer/undefined/overview (note `undefined`)

## Screenshots
![Screenshot 2024-02-05 at 10-57-04 Polar - Pledge for progress](https://github.com/polarsource/polar/assets/51661/0d3ee0d1-e1dd-4b49-9744-dc003d8c63ce)

![Screenshot 2024-02-05 at 10-57-26 Polar - Pledge for progress](https://github.com/polarsource/polar/assets/51661/cefea89f-0c23-4d45-a67a-6d7de09456a1)

![Screenshot 2024-02-05 at 10-57-42 Polar - Pledge for progress](https://github.com/polarsource/polar/assets/51661/621e857b-323e-44a3-9660-a71416663a80)

**Comment by zegl** [comment]
Thanks for a great bug report! I'll investigate and see what's up.

**Comment by zegl** [comment]
Fixed in #2465
