### ISSUE TITLE
Copied code contains line-numbers

### ISSUE THREAD

**Issue by eval** [polarsource/polar#2482]
Copying this from an article:
![Screenshot 2024-02-06 at 17 07 41](https://github.com/polarsource/polar/assets/290596/674ba7f8-17fc-4335-9dd7-dd9b62140032)

...pastes this:
```
(defn run [lexer]

2  (loop [{lex-fn :state :as lexer} lexer] ;; 1.

3    (prn lexer) ;; 2.

4    (if-not lex-fn

5      lexer

6      (recur (lex-fn lexer))))) ;; 3.
```

I mean, Clojure looks weird, but it shouldn't look _that_ weird ;)

**Comment by zegl** [comment]
> I mean, Clojure looks weird, but it shouldn't look that weird ;)

LOL

**Comment by eval** [comment]
🚀  Thanks!
