### ISSUE TITLE
Feature Request: Yearly recurring subscription tiers

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#2534]
We've received feedback that it would be nice to configure certain tiers as paid yearly instead of monthly.

**Comment by emilwidlund** [comment]
How much of a hassle would this be to implement? @frankie567

**Comment by frankie567** [comment]
We talk about it with @birkjernstrom this morning. I think it's achievable in maybe ~2 days of work. Stripe handles this, from what I remember.

**Comment by birkjernstrom** [comment]
Great feature request and definitely worth having in our backlog as per our discussion yesterday. Chatted some more with the users interested in this. I asked whether "pay once" would be preferable which was a feature we discussed internally yesterday - thinking it might be an even better solution. However, their preference would be an annual subscription even with such a feature.

Some considerations then to this feature are:
- Ability to configure tier to be `annual`, `monthly` or `both`.
- Set individual prices for `annual` vs. `monthly`.
- How we showcase tiers with `both`, e.g showing a discounted monthly price in the annual subscription.

**Comment by frankie567** [comment]
*WIP in #2852* 

---

Work is progressing well, and the backend machinery with Stripe is in place and working well. I've a few edge cases I'm unsure how to tackle.

## The monthly/yearly switch

The switch makes sense if tiers have both a montly *and* a yearly pricing. Problems arise if:

* 👉 There is only monthly pricing / There is only yearly pricing. In this case, the straightforward solution is to hide the switch. However, it may cause some confusion for the user (if they don't pay attention, they might not see an organization actually applies a yearly-only pricing).
* 👉 Some tiers have a monthly/yearly pricing, but not the others. In this case, we have to show the switch, but it only has effect on the concerned tiers. That's a bit weird. Example below:

<img width="1086" alt="Capture d’écran 2024-03-15 à 14 54 51" src="https://github.com/polarsource/polar/assets/1144727/66489b86-f4a4-4344-8d2f-6c3b1fc53caf">

## The MRR stats

What does MRR mean for a yearly subscription? The solution I imagined was to divide yearly subscriptions amount by 12, so the amount is smoothed over a year. But not sure it fully makes sense.

<img width="1840" alt="Capture d’écran 2024-03-15 à 14 59 08" src="https://github.com/polarsource/polar/assets/1144727/4b132a59-73f5-4fd8-aa47-69c2fb2c02a9">

**Comment by birkjernstrom** [comment]
Great work @frankie567. It's going to be great to get this in-place. My thoughts on this are inline below.

## Yearly vs. monthly pricing

> There is only monthly pricing / There is only yearly pricing. In this case, the straightforward solution is to hide the switch. However, it may cause some confusion for the user (if they don't pay attention, they might not see an organization actually applies a yearly-only pricing).

I think that's fine. We should make the design in the tiers so clear that the switch is simply an additional indicator. It makes the most sense to hide it then in case there are no such options.

> Some tiers have a monthly/yearly pricing, but not the others. In this case, we have to show the switch, but it only has effect on the concerned tiers. That's a bit weird. Example below:

Let's filter out all tiers that do not have pricing for the given choice, i.e filter out all annual tiers only in case of monthly and vice versa. I think that makes the most sense.


## MRR

I see two approaches here.

**Amortized/prorated by month**
This is how we need to do it from an accounting perspective. Including for monthly subscriptions spanning between two months. E.g calculating the given months % contribution to the full amount and accounting that percentage to the given month.

However, I don't think that's intuitive or what most people would expect at all. So instead, I'm in favour of...

**Earnings vs. MRR**
I think we should change name to "Earnings" or equivalent and drop the MRR piece. Just reflecting the money coming in any given month – both monthly subs, pledges, annual subs etc. Going to be the most simple and straightforward way that will support all future revenue/funding streams that we'll introduce. I also think it's what most people would expect to see.

**Comment by frankie567** [comment]
Ok, overall!

> **This is how we need to do it from an accounting perspective.** Including for monthly subscriptions spanning between two months. E.g calculating the given months % contribution to the full amount and accounting that percentage to the given month.

That greatly scares me. Do you mean yearly subscriptions have to be handled specifically in our transactions? In the current setup, if we receive $X for a creator (whether it's a monthly or annual subscription), it'll create **one** transaction on their account; and money will be available to payout immediately.

**Comment by birkjernstrom** [comment]
> > **This is how we need to do it from an accounting perspective.** Including for monthly subscriptions spanning between two months. E.g calculating the given months % contribution to the full amount and accounting that percentage to the given month.
> 
> That greatly scares me. Do you mean yearly subscriptions have to be handled specifically in our transactions? In the current setup, if we receive $X for a creator (whether it's a monthly or annual subscription), it'll create **one** transaction on their account; and money will be available to payout immediately.

Oh no, not at all - sorry for raising your pulse there 🙂 You don't have to do anything differently in terms of how payment, balances & payouts are done. This only impacts how do reporting internally to our accountants. Explanation below for context.

Let's say you have Developer A getting the following transactions on March 18th, 2024:
1. Annual subscription of $300 until March 18th, 2025 
2. Monthly subscription of $5 to be billed again on April 18th, 2024

We would charge for those both immediately on March 18th, 2024 and upfront when they happen, i.e $305 in total. From there we deduct Polar & Stripe fees before issuing payouts. So Developer A might get $280 (rough calculation) a few days later on March 24th let's say.

However, on the accounting side it's different and impacts how we need to generate reports (SQL) of such payment activities. You need to recognize revenue for each standalone month even though the cash flow would be $305 all at once. E.g
1. Annual subscription. How many days in March was it active. How many days is that / total yearly days. That % should be recognized for March. Same then for April, May.. and onwards. Similar to the below, but over the course of the full year vs. month.
2. Monthly. E.g $5 for March 18 - April 18th means that we need to account (31 - 18) / 31 (41.9%) of $5 ($2.1) in March vs. $2.9 in April.

I hope that clarifies things 🙂
