### ISSUE TITLE
Posts: <iframe> / YouTube embed does not work in emails

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#2567]
<img width="561" alt="Screenshot 2024-02-15 at 14 26 27" src="https://github.com/polarsource/polar/assets/47952/7b582fd9-7c99-4e64-93ab-50c7bbe1e209">

**Comment by frankie567** [comment]
Fixed it earlier today: 671c674635c8c08ffba249d06a7b55aabff25fe4 😄

**Comment by zegl** [comment]
oh, perfect! :D
