### ISSUE TITLE
GitHub: Create discussion from post

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2629]

**Comment by webbdays** [comment]
is it live?
I would like to work on this.
Thanks.

**Comment by birkjernstrom** [comment]
@webbdays No it's not. However, it's not highly prioritized in the short-term (next month) and needs to be flushed out a bit in terms of how we want it to work exactly. So I don't think it's a good first issue at this stage to be honest, but appreciate your desire to contribute. 

I see that you've setup a Polar account - that's awesome! Would love to hear if you've run into any enhancement you would want personally? If so, I think those first type of contributions are the best and that we can start with a short review/discussion of that proposal via an issue before you dive in.
