### ISSUE TITLE
Custom domain

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2632]
Customer feedback to be able to set a custom domain (CNAME) to their Polar page.

- [x] Support rendering public pages on custom domain (`example.com/posts` is equivalent to `polar.sh/exampleorg/posts`)
- [x] Allow custom domains to CORS on `api.polar.sh`
- [x] Cross site authentication? 
- [x] In-app links to custom domain. Link to `example.com/...` instead of `/exampleorg/...` everywhere (last least cover all non-admin pages).
- [x] Redirect non-custom domain version to custom domain version (`/exampleorg/...` -> `example.com/...`)
- [ ] Automatic configuration of Vercel Domains (A/CNAME and TXT verification)
- [ ] Setup instructions
- [x] Logging out? Should logging out on one domain log out out everywhere?
- [x] New routes for repositories? `example.com/repository/{name}`? 
- [x] Posthog tracking

**Comment by zegl** [comment]
I think that this is pretty much done! We're missing A interactive setup guide, but that will come later, when we've figured out pricing etc etc.

For now: If anyone wants to setup a custom domain for your polar.sh page, reach out on our Discord, and we'll help you!
