### ISSUE TITLE
Polar Balance & Payouts v2

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2640]
Currently, our account, balance & payout structure is quite coupled with Stripe – transferring funds immediately and trigger corresponding payouts frequently.

We want to decouple it (lot of advantages) and streamline the flow to offer:
- Better overview of balance on Polar
- Potential usage of balance on Polar within Polar in a given timeframe, e.g donations to dependencies
- Manual withdrawal (automatically scheduled later) to reduce fee impacts
- Polar to model the PSP (1:1) & Polar fees. Deducting them upfront for transparency, clarity and easy accounting vs. ad-hoc (as they charge Polar).
- Future: Connect other payout methods, e.g PayPal, Wise and others (more international coverage).

![Image](https://github.com/polarsource/polar/assets/281715/71662928-2797-41ae-9acb-6ca2188d7c27)

**Big todos**
- [x] Introduce Polar balance with manual withdrawal to Stripe, i.e user triggered transfer & payouts (impactful and helpful to save on fees later)
Main decoupling stage unlocking this model and all future opportunities.
- [x] Polar model for Polar & PSP fees – still waived until after March 31st 
- [ ] Receipts (PDF/CSV) downloads for Polar transfers reflective of the above

**Comment by frankie567** [comment]
Reopening, because we don't have receipts yet, he he 😝
