### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2641]
Webhooks:
- Subscription
- Issue funding
- Benefit granted
- Benefit revoked

**Comment by JacobCoffee** [comment]
Preferably these could be channel independent e.g., I would want to post webhook events for subscriptions, funding, and pledges to public channels but the others would be bound for admin-only channels

**Comment by birkjernstrom** [comment]
Thank you @JacobCoffee, I think you mean the Discord webhooks, right? This short proposal was more focused on generic Polar Webhooks for API integrations. But definitely a short written issue without a lot of context :)

**Comment by zegl** [comment]
I recently found [Standard Webhooks](https://www.standardwebhooks.com/), which seems to be an industry attempt at defining best practices for webhooks.
