### ISSUE TITLE
App blocks migrations

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#265]
I've found that sometimes, the backend apps, either the API or the worker. Holds locks in the database that prevents alembic to run migrations.

This is fine locally, but in production it can causes deployments to fail (not every time, but sometimes).

When the deployment fails, we have to SSH into the old instance, and kill it, which allows the new instance to run the migrations and boot up again.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/265">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/265/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/265/pledge.svg">
</picture>
</a>

**Comment by hult** [comment]
What would be a solution? Have the app connect to a read replica while the main db is upgrading?
