### ISSUE TITLE
Have a separate worker queue for GitHub jobs

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#2761]
This morning, we had some timeout and rate limit errors on lot of GitHub sync jobs, which delayed processing of new jobs by almost an hour:

<img width="1033" alt="Capture d’écran 2024-03-06 à 09 24 26" src="https://github.com/polarsource/polar/assets/1144727/cd6d5141-f0fe-404c-a4c5-86baa1f79b69">

It happens rarely but we have critical jobs (like Stripe subscriptions events) which should be handled quickly.

To avoid this, we could have a separate queue with a dedicated process only for GitHub sync, while leaving the other for critical jobs.

**Comment by zegl** [comment]
_(this is not a blocker for your idea above)_

Agreed, and truth be told! A _lot_ of these GitHub syncs can probably be removed. We're barely using issue_references and issue_dependencies, and they are a majority of all jobs executed!

**Comment by frankie567** [comment]
Great call, @zegl. I even think it could be the first thing to consider before thinking about complex things like I propose above :) I'll open an issue for this!
