### ISSUE TITLE
Remove IssueReference and IssueDependency models and logic

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#2771]
As pointed out by @zegl in #2761, we are putting great efforts in synchronizing issue references and issue dependencies. Lot of code to maintain, lot of computation power spent for a feature that's not really used.

Since we'll likely adjust the vision around issue funding, it might be good to consider removing this; and only focus on synchronizing direct issues and pull requests. I believe it'll save us lot of headaches 😄

Would like to have your inputs on this, @birkjernstrom 😊

**Comment by birkjernstrom** [comment]
Agree. Chrome extension is another nice negative PR around the corner 🙂

So let's get rid of it. However, now as we're adding the ability to highlight initiatives on your page with the potential desire to add any repo there, we might want a slim version of the "synchronizer". One that syncs a given repo vs. crawls for dependencies though - that part we can definitely drop. In our chat on Monday we'll talk about that page together so we're all on the same page. Depending on that outcome we'll know if we remove 100% or 80%+ here.
