### ISSUE TITLE
Cloudflare blocks suspicious commands in posts content

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#2814]
As reported in Discord: https://discord.com/channels/1078611507115470849/1205077924865249290/1216795063070494853

Sample payload:

```md
`curl -fsSL https://`
```

**Comment by zegl** [comment]
I've reached out to Render and asked if we can configure and/or disable the WAF for our service.

**Comment by frankie567** [comment]
Thanks :)

I'm wondering if we migrate to Cloudflare, we could then be in control of those settings; hoping then we won't pass again the WAF filters when entering the Render infrastructure (since we would be Cloudflare to Cloudflare).

That's a move I wanted to make for some time, the DNS records manager in Namecheap is unbearable!
