### ISSUE TITLE
Posts: brackets in markdown link texts does not work

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#2815]
Example:

E.g [`#[pyclass]`]( https://pyo3.rs/v0.20.3/class#defining-a-new-class).

```
E.g [`#[pyclass]`]( https://pyo3.rs/v0.20.3/class#defining-a-new-class).
```

**Comment by zegl** [comment]
Huh, this seems to be a bug in the markdown parser of `markdown-to-jsx`. I'll see what I can do.

**Comment by birkjernstrom** [comment]
Love that you pledged toward the issue 😍
