### ISSUE TITLE
Codespace: setting up test db

### ISSUE THREAD

**Issue by patrick91** [polarsource/polar#2846]
Hi there! I was looking into running the tests on the codespace, and when running it by default you get an error saying the `polar_test` db doesn't exist. 

To make it work I had to

1. copy the `.env.testing` to `.env`
2. run `poetry run task db_recreate`

Do you think we could add something like this to the setup? 

One option is also to update the dockerfile to also create the test db, but not sure what's the preference here 😊

**Comment by birkjernstrom** [comment]
Nice catch @patrick91 and thanks for creating the issue.

Yes, this would be a nice DX enhancement we should do. As a quick fix I'm adding some documentation in our README about this as a workaround. The best solution is simply to create an empty `polar_test` database. From there you can run the tests which will setup all the required schemas (just not the db). Automatically creating the `polar_test` db in Codespaces would certainly make things easier though and a worthwhile enhancement.

**Comment by frankie567** [comment]
I've added that automation to our Codespace setup. The DB `polar_test` will be automatically created on Codespace *creation*.

If you want to create it on an existing Codespace, you can run the following script:

```sh
./bin/create-test-db
```
