### ISSUE TITLE
Enhancement: Prettify embed

### ISSUE THREAD

**Issue by JacobCoffee** [polarsource/polar#2864]
Embed has a lot of room to to made nicer e.g.,

## Current
<img width="581" alt="image" src="https://github.com/polarsource/polar/assets/45884264/39f41a40-ec7b-41e4-9860-e8c49c6097b2">

## Proposed
<img width="529" alt="image" src="https://github.com/polarsource/polar/assets/45884264/cef1f941-2530-437b-a627-a86d2c009688">

## other examples

<img width="588" alt="image" src="https://github.com/polarsource/polar/assets/45884264/633f3cc1-6639-41d2-8e1b-466dd49e0576">

**Comment by emilwidlund** [comment]
Thank you @JacobCoffee for contributing to close this issue! ⭐

The rewards from this issue, totalling $30, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
