### ISSUE TITLE
Embeddable tier picture is not updating

### ISSUE THREAD

**Issue by PeterWaIIace** [polarsource/polar#2946]
Hey,

It seems that after changing highlighted tier it changes only on the polar.sh but it does not affect embeddedable picture in promote section (the one from under the link). Hence I cannot update my github project page, it is minor inconvenience. If that update requires some time then maybe it would be worth to add such message to let user know.

Thanks!

**Comment by zegl** [comment]
Thanks, yeah, seems like something is cached for too long.

cc @emilwidlund

**Comment by emilwidlund** [comment]
@PeterWaIIace Thanks for the bug report. #2949 will fix this.
