### ISSUE TITLE
[Minor bug] Pictures/Gifs not showing in posts if there is no preceding text

### ISSUE THREAD

**Issue by PeterWaIIace** [polarsource/polar#2953]
**Description**: I was just trying to make a post with a GIF, and for some reason, after posting it, my picture just disappeared. I tried to edit it and save it a few times, but only after adding one line of text before the picture itself was added to the post. It works fine in preview mode, though, so it was a bit confusing for me at first.

**Issue**: It appears that media cannot be first line of polar's markdown posts for now.

**Comment by zegl** [comment]
Thanks for the report, I'll take a look! 👀

**Comment by zegl** [comment]
@PeterWaIIace I'm unable to reproduce this, do you remember what your markdown input looked like?

I _suspect_ that this might have been related to a cache invalidation issue, which I fixed in #2954. Could you please test again, and see if the issue remains?

**Comment by PeterWaIIace** [comment]
Tried to reproduce, but it seems to work fine now!
