### ISSUE TITLE
Bug: Tier edit view issues

### ISSUE THREAD

**Issue by JacobCoffee** [polarsource/polar#2964]
## Issue

- Tier edit view doesn't show all tiers
  https://polar.sh/maintainer/litestar-org/subscriptions/tiers
  but does in public view: https://polar.sh/litestar-org/subscriptions
Public:
<img width="959" alt="image" src="https://github.com/polarsource/polar/assets/45884264/70a74e74-020e-46bd-98f2-740549b13f2a">
Private:
<img width="949" alt="image" src="https://github.com/polarsource/polar/assets/45884264/d036b0bb-5638-4835-99ba-be013a834952">

- Tier view doesn't show cost per month (but only for businesses)
<img width="233" alt="image" src="https://github.com/polarsource/polar/assets/45884264/5fe54050-95b5-4328-986e-6b9273fbacfc">
<img width="631" alt="image" src="https://github.com/polarsource/polar/assets/45884264/df53220e-f04c-436a-995f-1d45b6456fb0">

Public:

<img width="600" alt="image" src="https://github.com/polarsource/polar/assets/45884264/217e372c-a4b9-4f22-abd8-254e025268dd">

**Comment by zegl** [comment]
Thanks for the bug report, and sorry for not responding here earlier. The bug has now been fixed, and the fix is rolling out as we speak. Please let me know if it's not fixed for you. :-)
