### ISSUE TITLE
Subscription: Downgrade to `Free` upon overdue payment

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3018]
I was a paid subscriber to an expensive tier (one-off agreement). Upon renewal, I had insufficient funds. Since the subscription was going to be cancelled anyway it was not a problem.

However, I was unsubscribed entirely vs. downgraded to `Free`.

**Comment by frankie567** [comment]
Handling this case is a bit tricky. When payment fails, Stripe changes the state of the subscription to *Past Due*. On our side, we indeed revoke the benefits (which looks a sensible behavior to me).

However, the subscription is still there, and Stripe hopes, that, at some point, the payment issue will be resolved and the subscription resumed (at which point we'll re-enable the benefits).

If we downgrade to a Free subscription, we would lose that opportunity and definitely lose the paid subscription.

**Comment by zegl** [comment]
Agreed that it makes sense to downgrade failed/cancelled paid subscriptions to _free_ subscriptions, but it's definitely a bit tricky to handle on our side.
