### ISSUE TITLE
all issues show a "closed" polar button

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#3103]
When I look at issues such as these: https://github.com/niccokunzmann/open-web-calendar/issues/320

I see that the button that usually invited people to fund issues, is now showing "closed".

![grafik](https://github.com/polarsource/polar/assets/564768/3b0296c1-dbb8-42d5-909d-e468d7ad0a25)

This seems to be the case for [all issues](https://github.com/niccokunzmann/open-web-calendar/issues/).
I think though that it is maybe only one issue that has been closed lately.

**Comment by zegl** [comment]
Oh, that's not good! Thanks for reporting, I'm taking a look....

**Comment by zegl** [comment]
The fix is out now! :)
