### ISSUE TITLE
[feat]: Allow searching through organizations and issues

### ISSUE THREAD

**Issue by pktiuk** [polarsource/polar#3191]
This issue is a followup to my comment from general GitHub discussion: https://github.com/orgs/community/discussions/4517#discussioncomment-9052153

In my opinion, Polar lacks discovery feature. 

It should allow two ways of discovering projects and issues:

1. Discovering for people willing to contribute. If I were a freelancer, I would like to have some way of filtering projects with rewards. (or maybe filtering issues with rewards). It would be handy to have filters for the project language etc.

2. Discovering for users. The most basic way of discovering polar projects for registered users would be showing polar projects among projects I already starred (there is a high chance I will support them). Showing some curated projects would also be handy.

**Comment by birkjernstrom** [comment]
Cleaning up our issues. Closing this given our discussion here https://github.com/orgs/polarsource/discussions/3661

Building discovery/marketplace for issue funding is not a focus of ours. We want to build the best platform for developers to get paid/funding vs. a marketplace for contributors which is better served by players such as Algora.
