### ISSUE TITLE
NextJS Starter Kit

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3246]
Ideally this starter kit and what the Polar page is are 1:1. But of course with the ability for the developers to easily make it their own on custom domains, sites & services.

**Comment by xn1cklas** [comment]
I would love to help out on this one! 

If I understand you correctly you would like the example to look like the polar homepage? I'd probably make it a bit sleaker. 

We could leverage these two repos and replace stripe with polar:

Vercel Supabase Starer
https://github.com/vercel/next.js/tree/3bb7415f38f823f514315f90f97ac03e595b7c4c/examples/with-supabase

Vercel Stripe Starter
https://github.com/vercel/nextjs-subscription-payments

**Comment by xn1cklas** [comment]
So I couldn't hold my hands still and build something:

It's a small next.js repo using polar. It was just a small mess around, but I'm looking forward to improving on it and add more frameworks like astro, nuxt and sveltekit soon.

Currently, supported features:

- fetching products from polar organization
- checkout as server action to subscribe to any displayed product

Deployment: https://next-polar-starter.vercel.app/

Github: https://github.com/xn1cklas/next-polar-starter/tree/main

Let me know if I can be of any help on this issue.
