### ISSUE TITLE
1% OSS Program

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3247]
Ability to set Polar developers/initiatives that funding/subscriptions/products should automatically donate x% to.

**Comment by Aslemammad** [comment]
I always had the thought of contributing for instance 10% of my income to other developers and projects in OSS! This would be amazing.

**Comment by birkjernstrom** [comment]
Glad to hear that @Aslemammad ♥️ I'm equally excited about it and think it can lead to some really exciting contributions & discussions. Hopefully even improve the conversion rate of sales, i.e people getting more excited to buy/fund something if they see it also goes to OSS upstreams.
