### ISSUE TITLE
Signup is glitchy

### ISSUE THREAD

**Issue by simonmichael** [polarsource/polar#3315]
I may be off with the details but it was something like: in Safari, I went to polar.sh, clicked the sign up with github button, authorized github, used the browser back button at some point in the flow, instead of seeing github auth sucess message saw an error page showing with message "something something maintainer something". (But signup & login were successful).

And right now, if I log out and click the sign up with github button again, I get a blank page.

**Comment by emilwidlund** [comment]
Hey @simonmichael - really sorry to hear that you had such a poor experience. That is certainly not how it should be. Sounds like you’ve encountered a weird state in our sign up flow. 

We’ll take a look at this first thing in the morning. We’ll get back in touch soon. 

Thanks!

**Comment by emilwidlund** [comment]
@simonmichael We found a missing relation regarding your user in the database. While we're trying to figure out how that happened, we've added it manuall so you should be able to login without issues. 

Let us know if the problem persists. Thanks!
