### ISSUE TITLE
Donation amount summary per author/organization

### ISSUE THREAD

**Issue by notramo** [polarsource/polar#3322]
I would like to see how much money each author/organization made.

When I open an author page, (e.g. https://polar.sh/sindresorhus) I want to see 
- total amount since registration
- current monthly revenue

I think this would have the following benefits:
- encourage more developers to join Polar
- see if a project is well-funded 
  - to help choose well-funded libraries/programs when designing the architecture of a new project
  - guess if a new project is expected to be successful

**Comment by birkjernstrom** [comment]
Apologies for not responding to this sooner @notramo. Reviewing & cleaning up our issues/discussions to better facilitate an open backlog and clean-up feature requests – moving them into discussions if relevant.

Unfortunately, I'm closing this as not planned. Our focus is to be the best platform for developers to get paid, but disclosing how much should default to being private unless the developer desires to disclose it themselves, e.g share screenshots of their metrics, leverage our API to automate generation of public dashboard etc. I don't think we should make that call on behalf of everyone.
