### ISSUE TITLE
Show `Cancels at <date>` in list of subscriptions in case `cancel_at_period_end` is true

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3346]
In case a subscription is for May 20 - June 20, but cancelled on May 25 it's still active until the period ends, e.g June 20th. At that point it will show up as cancelled in our UI. However, it would be nice to also showcase active subscriptions that are about to be cancelled if that is indeed the case.

By having a small pill showing `Cancels at <date>` when that is the case.

**Comment by frankie567** [comment]
Shown as described in the individual subscription page (`/purchases/subscriptions/XXX`)

**Comment by robingenz** [comment]
> Shown as described in the individual subscription page (`/purchases/subscriptions/XXX`)

Is there a way for organizations (`/maintainer/.../sales/subscriptions`) to check when a customer has canceled their subscription? That was the actual idea behind it when I wrote @birkjernstrom. ^^

**Comment by frankie567** [comment]
Ha, right, I misunderstood this! Reopening 🙂

**Comment by frankie567** [comment]
So, *this time* a fix is underway for this 😄

Basically, a yellow badge is now added in the *Status* column for subscriptions pending cancellation. 

<img width="1325" alt="Capture d’écran 2024-06-24 à 10 43 25" src="https://github.com/polarsource/polar/assets/1144727/55b002c1-52bd-407a-bde6-d97e3de13ff4">

I also tweaked the *Status* column sorting so pending cancellations rows are sorted above/below the active rows.

**Comment by robingenz** [comment]
Looks great, thank you! 🎉
