### ISSUE TITLE
API Reference docs improvement

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#3359]
Here are a few things I've noted while browsing the API reference 😊

* [x] Hide endpoints that do not have the tag `public`

Others are internal endpoints that should not be displayed to the user

---

* [x] Collapse sections? (it can be quite long to scroll)

<img width="1840" alt="Capture d’écran 2024-05-28 à 10 39 08" src="https://github.com/polarsource/polar/assets/1144727/cd3912b0-7e68-4e17-a882-bc4cbe80705e">

---

* [x] Show the endpoint's description (Markdown supported)

<img width="1840" alt="Capture d’écran 2024-05-28 à 10 21 47" src="https://github.com/polarsource/polar/assets/1144727/a2edf256-842a-4eac-8a56-82231d81081c">

---

* [x] Show the endpoint's required scopes

<img width="797" alt="Capture d’écran 2024-05-28 à 10 22 49" src="https://github.com/polarsource/polar/assets/1144727/86aa95de-a11b-416f-b1ea-c093359636b0">

---

* [x] Support Markdown on parameter's description

<img width="845" alt="Capture d’écran 2024-05-28 à 10 24 23" src="https://github.com/polarsource/polar/assets/1144727/473e334c-cde0-4bb7-b976-3688185f2c7c">

---

* [x] Show parameter's types

<img width="797" alt="Capture d’écran 2024-05-28 à 10 25 27" src="https://github.com/polarsource/polar/assets/1144727/b4353915-a1e7-4231-ab60-6143beb09f97">

---

* [x] Show a label for optional parameters

<img width="810" alt="Capture d’écran 2024-05-28 à 10 38 16" src="https://github.com/polarsource/polar/assets/1144727/5a65de93-1d31-42d5-854c-f24e5f8c1b71">

---

* [x] Handle unions types for payloads

<img width="846" alt="Capture d’écran 2024-05-28 à 10 28 02" src="https://github.com/polarsource/polar/assets/1144727/9dad5dd9-6099-4548-a814-2ce7ffe5c7d7">

<img width="845" alt="Capture d’écran 2024-05-28 à 10 28 30" src="https://github.com/polarsource/polar/assets/1144727/ff7d1fa4-8c47-40c1-ac9a-9d6501c69bc3">

<img width="839" alt="Capture d’écran 2024-05-28 à 10 28 57" src="https://github.com/polarsource/polar/assets/1144727/6070ffe6-8de4-4bbf-ab73-60fc5847e04b">

<img width="853" alt="Capture d’écran 2024-05-28 à 10 29 21" src="https://github.com/polarsource/polar/assets/1144727/5cb4c3ab-997c-4ef4-b50a-e846d7360f3a">

**Comment by emilwidlund** [comment]
@frankie567 I can't find the `public` tag being used in our schema? Looking at the source.json in the SDK.
