### ISSUE TITLE
GitHub Action: Upload releases as file downloadables

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3457]
Can be made in https://github.com/polarsource/actions

**Feature**
A GitHub Action for Polar to automate publishing a GitHub release as a file downloadable on Polar using our [Files API](https://polar.sh/docs/api-reference/api/v1/files/post)

**Expectations**
Let us know before you want to start working on this so we can help & offer support if needed + avoid any issues down the road with a surprise PR.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/3457">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/3457/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/3457/pledge.svg">
</picture>
</a>

**Comment by brymut** [comment]
Hi, @birkjernstrom, I would like to try take this on. Is this possible?
I'm a web-dev & based on my previous experience working on projects that used Github actions to manage releases & testing methods in their respective CI/CD processes. I understand how I can implement it here to publish releases on Polar via events on repositories to the respective endpoints on Polar's API.

**Comment by birkjernstrom** [comment]
Thank you @brymut following up from our [Discord discussion](https://discord.com/channels/1078611507115470849/1151973214562558085/1275600495553282151), but the tl;dr from that for others seeing this thread is:

- Awesome that you want to work on this. You're assigned. No permission grant required upfront, but...
- Great if you create a PR draft, discuss it on Discord and keep us in the loop vs. work in silent and create a bigger PR later - worse experience for everyone vs. frequent feedback & smalle reviews/guidance.
- As a starting point it would be great to get a short write-up on how you imagine building this that we can align on

**Comment by birkjernstrom** [comment]
Closing this.

No progress or actions made, and with time this feature has become less relevant and not something we've seen customers request.

So closing to stay focused on all of the efforts our customers request from us 🫡
