### ISSUE TITLE
Benefit: License Keys

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3459]
A new Polar product/subscription benefit to offer license keys to community or commercial customers.

**Comment by matmair** [comment]
It would be nice if license key verification could work offline. A common mechanism for that is using public/private certs To sign license keys. See https://github.com/keygen-sh/example-python-cryptographic-verification/blob/master/main.py as a reference how keygen handles that.

**Comment by birkjernstrom** [comment]
Thank you @matmair! Really appreciate the example for additional context – I've looked at Keygen and really like their service.

**Comment by matmair** [comment]
Feel free to reach out if you need some insights on the problems with deploying licensing in air-gapped environments. I am self-hosting keygen and using it to provide off- and online licensing for digital *things*.
