### ISSUE TITLE
Can't become creator again after deleting installation

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3500]
**Problem**
- User had a personal organization (`created_from_user_maintainer_upgrade=True`)
- Installed the Polar GitHub App
- Later uninstalled the Polar GitHub App causing the organization to get a `deleted_at`
- Could not re-create their personal organization (404 upon clicking "Become creator")

**Solution**
Currently, we're only checking if a record exists in the upgrade path and aborting if it does. However, we would need to change the `deleted_at` status too since the later flow fetches active organizations. Causing the 404 in this scenario due to no active (non-deleted) organizations existing.

**Comment by frankie567** [comment]
This is no longer the case now that Polar Organizations are independent from GitHub :)
