### ISSUE TITLE
Docs: Hide legacy endpoints and document upcoming ones

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3537]
We have *a lot* of endpoints and many of more internal nature. Let's hide them to focus on the endpoints that will power the use cases we believe are of interest.

**Endpoints/cases to focus on**
- OAuth & Gatekeeping
- Newsletter Subscriptions (embed/signup subscribers)
- Products (Subscriptions & Products)
- Benefit Grants
- Articles/Newsletters

Separately we can create a page for "Changelog" & "In progress" and in the latter we can communicate that the issue funding endpoints and others are still TBD to be ported over to our new form of API, but that we invite developers to join our Discord if they want to integrate them specifically.

**Comment by frankie567** [comment]
First part re: hierarchize endpoints done ✅

The doc page about hidden endpoints is still to do
