### ISSUE TITLE
GitHub Organization Installation triggers `HTTP 500` for unknown reason

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3559]
![image](https://github.com/polarsource/polar/assets/281715/d66a4fc0-5104-4da1-add3-19727a922689)
![image](https://github.com/polarsource/polar/assets/281715/b5a5ac4e-c5ae-4cf7-9e6d-1e1a676b2deb)

**Comment by frankie567** [comment]
I see there is an error 500 returned by `/integrations/github/installations`. I think that's the problem; browser complains about CORS because HTTP 500 responses miss the right CORS headers.

**Comment by birkjernstrom** [comment]
What would I do without you @frankie567 😅 Classic. You're absolutely right. I don't know how many times I've been bitten by this that a 500 triggers this and that the CORS console error showing up first makes you miss the actual issue.

But this is good news. I'll fix the 500 here. + Update issue title.

**Comment by birkjernstrom** [comment]
Closing this in favour of https://github.com/polarsource/polar/issues/3562
