### ISSUE TITLE
Extension: Publish to the Chrome Web Store (copy & assets needed)

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#362]
- [ ] screenshots, must be 1280 by 800
- [ ] description

Our listing (draft): https://chrome.google.com/webstore/detail/flgggfbldmglpjmagkhlhiohnkcmgbhi/preview?hl=en&authuser=0

**Comment by birkjernstrom** [comment]
Submitted a few hours ago 💪🏼🚀
