### ISSUE TITLE
Missing languages in client-side code highlighter

### ISSUE THREAD

**Issue by eval** [polarsource/polar#3622]
A markdown code block won't have syntax highlighting when previewing a post. For published articles it's shown correctly.

**Comment by frankie567** [comment]
Hey @eval 👋 

Thank you for reporting; however, I don't experience the bug you describe.

<img width="1168" alt="Capture d’écran 2024-07-09 à 15 19 17" src="https://github.com/polarsource/polar/assets/1144727/01013deb-3489-4e67-8095-03f956490051">

Could you share the post (or the faulty part) that provokes the issue?

**Comment by eval** [comment]
Thanks for checking @frankie567 It's seems to be specifically for clojure code blocks from this post: https://polar.sh/eval/posts/named-capturing-groups-in-clojure.

So the code in the post looks differently than before, and in preview mode no highlighting is visible...

**Comment by frankie567** [comment]
Ah ok, I understand now :) We're using a light bundle of Shiki for client-side highlighting, which probably doesn't embed Clojure. The post page is server-side rendered so we're able to load languages on demand — that's why it works there.

I'll see what I can do 👍
