### ISSUE TITLE
"Badged" link hard to discover

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#3690]
When I view the issue list, I can see "badged":

![grafik](https://github.com/user-attachments/assets/a1eb2d01-19a1-4292-a962-462ff6b63fc7)

What I really want to see is a button: "edit":

![grafik](https://github.com/user-attachments/assets/3b12486f-53c4-4dae-b17e-9f13ff9735f6)

An action word would mark this as an action but actually it is just "badged" which suggests that this is a passive state.

**Comment by emilwidlund** [comment]
Fixed by #3702.
