### ISSUE TITLE
"Confirm completed issue" transactional email CTA didn't let me log in

### ISSUE THREAD

**Issue by vcarl** [polarsource/polar#3743]
This email included a link to take action: 
![image](https://github.com/user-attachments/assets/161ac9a1-012c-466a-96ac-6027cc01a893)

But I was logged out, and the screen only provided me with options to create a new organization (on the page `https://polar.sh/dashboard/create`), without a way to log in. I had to go back to the homepage, log in, then open the page again.

(also the email gives me links to the right page, but a big CTA button with "Confirm completion" might be more effective here!)

**Comment by birkjernstrom** [comment]
Cleaning up our issues to move towards a fully open backlog and better issue structure. 

Closing this issue. During August, we changed our redirect/flow for signups and had a momentary issue that would explain this behaviour at the time. It was addressed and now we only redirect to `/dashboard/create` in case of explicit signups with the intent of being a `creator`, e.g developer selling, getting funding etc.
