### ISSUE TITLE
issues/overview: missing repository in filter

### ISSUE THREAD

**Issue by rsteube** [polarsource/polar#3769]
### Current Behavior

Repository [carapace-bin](https://github.com/carapace-sh/carapace-bin) is missing in the filter of [issues/overview](https://polar.sh/dashboard/carapace-sh/issues/overview) (Creator Dashboard).
It is however activated and issues from it are visible for `All Repositories`.

### Expected Behavior

List `carapace-bin` as drop-down option.

### Anything else?

![image](https://github.com/user-attachments/assets/cf8fe870-6832-4aa0-8205-e2fb590f9d62)

**Comment by frankie567** [comment]
That's probably a pagination issue (we only load 10 items instead of iterating over all the available ones).

Will fix it ASAP, thank you for reporting it 👍
