### ISSUE TITLE
benefits: crash when trying to create new `Github Repository Access` type

### ISSUE THREAD

**Issue by rsteube** [polarsource/polar#3785]
### Current Behavior

Crash when trying to create a new Benefit with type `Github Repository Access` for [tabdance](https://polar.sh/dashboard/tab-dance/products/benefits).

### Expected Behavior

Succeed, or show error message (as it's likely a botched configuration somewhere).

### Steps To Reproduce

1. `Create Benefit`
2. Choose `Github Repository Access`
3. Wait while repositories are being loaded (spinner shown)
4. crash

### Anything else?

![image](https://github.com/user-attachments/assets/8c46d4b4-53cf-463f-a386-66fe1c1c5417)

![image](https://github.com/user-attachments/assets/4856e3dd-23b6-40bd-bb33-8766bfa68023)

**Comment by frankie567** [comment]
Hi @rsteube 👋  Sorry for that! It looks like our error handling was indeed faulty here.

You should now see a proper error message. In your case, it'll require you to click on **Reconnect** to get a fresh access token from GitHub.

Let me know how it goes!

**Comment by rsteube** [comment]
Ok, I got it now. Took me a while, because I didn't see the `Reconnect` link.
The error messge was shown without crash.

**Comment by frankie567** [comment]
Nice! Thank you for reporting the issue 🙏
