### ISSUE TITLE
Cannot find where to add a new repository

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#3797]
Where would I add a new repository? I cannot find the option.

I would expect it here: https://polar.sh/dashboard/niccokunzmann/issues/overview
Something like a `+ add repository` button, e.g. here: 
![image](https://github.com/user-attachments/assets/5d14cd7a-e7ce-4c8f-8cb3-92d22b6927b8)

Or in the settings: https://polar.sh/dashboard/niccokunzmann/settings

Actually, I would like to visit the new repo's page and create it... (ics-query being the new repo)
https://polar.sh/niccokunzmann/ics-query

**Comment by frankie567** [comment]
Hey @niccokunzmann 👋 

That's indeed not very obvious. You need to go to **Organizations** tab and click on **Manage installation**. You'll be taken to GitHub where you'll have a chance to add new repositories. They'll then sync on Polar automatically.

<img width="1300" alt="Capture d’écran 2024-08-23 à 16 56 28" src="https://github.com/user-attachments/assets/85c603e3-fb2b-4032-b11b-0e36d7be846e">

Let me know how it goes!
