### ISSUE TITLE
Confusing PR icons

### ISSUE THREAD

**Issue by Netail** [polarsource/polar#3807]
Hello,

The current related PRs list displays a red + closed icon when a PR has been merged, this is a little confusing as it hints that those PRs have not been merged. An alignment with GitHub (purple with a merged icon) would be nice :)

<img width="684" alt="Screenshot 2024-08-27 at 11 57 04" src="https://github.com/user-attachments/assets/7a98f54f-da64-439a-bdc9-fa23ea631966">

<img width="992" alt="Screenshot 2024-08-27 at 11 58 47" src="https://github.com/user-attachments/assets/64b36b14-3c8f-446d-a729-36ab2e778e9a">

Closed PRs are probably not shown in the PR list at all, so to make a clearer difference between open & merged was done like this. But from a visual & pattern recognition point of view (and initially now knowing closed PRs are not even shown), it can be a little confusing

**Comment by birkjernstrom** [comment]
Thank you @Netail for reporting this. We're taking a look now.

**Comment by emilwidlund** [comment]
This is definitely a bug in our backend. Looks like we have merged_at set, but not is_merged.

<img width="573" alt="image" src="https://github.com/user-attachments/assets/56c0050c-7cbb-4870-ad2d-7834169f255e">

We probably shouldn't have an explicit column for "is_merged", as we can infer that state from the timestamp.

Looping in @frankie567 here as he probably has better knowledge about what could have happened here.

**Comment by frankie567** [comment]
I think you're right here, @emilwidlund. Normally, `is_merged` is updated using `merged_at`, but for some reason, it was not. I'll convert that to a computed attribute.

**Comment by frankie567** [comment]
That's it, thank you for the report @Netail 🙏 

<img width="664" alt="Capture d’écran 2024-08-28 à 10 12 42" src="https://github.com/user-attachments/assets/7ee62679-39bf-453d-b467-f623f164646b">
