### ISSUE TITLE
Isaac great feedback Aug 30

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#3828]
Context: Isaac is on Windows. 

**Dashboard Generic**
- [ ] Prettify scrollbars to make it look better
- [x] Remove unnecessary links in the navigation to create more space + reduce overflow
![image](https://github.com/user-attachments/assets/af4e04a3-3c58-47fc-9227-0e714552c654)

**Account Setup**
- [x] Provider dropdown is unreadable
![image](https://github.com/user-attachments/assets/4158c29c-a679-4946-b7d2-b15bcc9a3a1c)
- [x] Strange overflow issue creating scrollbars
![image](https://github.com/user-attachments/assets/8130e85c-0f3e-4258-8519-73b16bef240a)
- [x] Can't read the text in the search input
![image](https://github.com/user-attachments/assets/49c78633-899f-4b06-b08d-aac9da5802a1)
- [x] Same with the collective name - not visible
- [x] Also would be good with some label/description
![image](https://github.com/user-attachments/assets/d05db2d3-d3ce-4440-b6a3-6d517746b215)

**Products**
- [ ] Fix dark background during upload creating a weird UI appearance
![image](https://github.com/user-attachments/assets/34a4266d-c545-4649-88e9-e1f0041c0bf6)
- [ ] No error handling for too high prices (lower priority short-term due to edge case nature)
![image](https://github.com/user-attachments/assets/0795ff92-a4d1-4de1-8336-aba800f6a700)

**Analytics**
- [ ] Hard to read metrics - too small
![image](https://github.com/user-attachments/assets/c6a565c7-679f-4080-a473-68c6aa1c2573)

**Webhooks**
- [x] Can't create webhooks it seems
![image](https://github.com/user-attachments/assets/d2389065-338a-4a66-b926-2f8c8227a817)
![image](https://github.com/user-attachments/assets/36e36297-54e5-4265-9e25-a2466ac7dd54)
![image](https://github.com/user-attachments/assets/9829b057-cb0f-491b-bf13-60603e75f0ef)

**Polar Page**
- [ ] Scrollbar on custom links
![image](https://github.com/user-attachments/assets/f93060d8-c5df-42c4-b055-854cef58b105)

**Docs**
- [x] Favicon
- [ ] Update signup instructions (outdated with the new `/signup` flow + Google too + GH decoupling)

**Issue Funding**
- [x] Fix border radius around issue comment in promotion
![image](https://github.com/user-attachments/assets/e5ea00ca-2c7c-40ac-bcc4-6f407c7aef18)

**Comment by isaacharrisholt** [comment]
![image](https://github.com/user-attachments/assets/1e0611c9-e633-4df6-bfca-6dddb7f49d89)

Publish menu for posts is missing

**Comment by birkjernstrom** [comment]
@isaacharrisholt Can you try again and check your network/console tab for any errors? It should send a POST to /articles to create it before modifying publication settings.

Separately working on some UX enhancements on that now to give more visual feedback of loading state

**Comment by isaacharrisholt** [comment]
@birkjernstrom 

```json
{
    "error": "RequestValidationError",
    "detail": [
        {
            "type": "value_error",
            "loc": [
                "body"
            ],
            "msg": "Value error, Either body or body_base64 must be provided.",
            "input": {
                "title": "test",
                "organization_id": "e68fc813-232a-4cd1-98a8-57544987b89e"
            },
            "ctx": {
                "error": {}
            }
        }
    ]
}
```

The post content is empty - is that what's causing it?

**Comment by birkjernstrom** [comment]
Yes. However, you shouldn't be able to click `Publish` though without a title + body – strange.  I'll look into it and improve this area a bit overall in terms of UX this evening. Unclear if I can solve the root cause for this issue tonight though, but now you now how to avoid it short-term. Need to get a windows machine up and running ASAP 🤓

**Comment by birkjernstrom** [comment]
@isaacharrisholt Fix deploying now in #3840 along with some UX enhancements. 

- Changed `Markdown` tab to `Editor`
- Editor & Preview contextually together
- Publish on the right-hand side with subtle visual attraction/button
- Preview settings now in the middle

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/8df48723-0c81-4d3d-9dc7-cdc755382f81">

**Comment by isaacharrisholt** [comment]
Docs for 'Get License Key' (`/license-keys/{id}/get` return a 404

**Comment by isaacharrisholt** [comment]
Promote button (per-issue badge modal) is a bit funky
![image](https://github.com/user-attachments/assets/2cb06232-6f74-4307-8391-8c4f8937c4c1)
