### ISSUE TITLE
Dark scroll bars on Light mode

### ISSUE THREAD

**Issue by ephraimduncan** [polarsource/polar#3888]
![CleanShot 2024-09-05 at 07 54 37@2x](https://github.com/user-attachments/assets/de9891f1-0120-4bbd-a8b0-176da1805b9c)

**Comment by birkjernstrom** [comment]
Oh wow that looks terrible indeed 😬 Windows & Chrome @ephraimduncan ?

**Comment by ephraimduncan** [comment]
Mac and Arc

**Comment by birkjernstrom** [comment]
Apologies for not following up on this @ephraimduncan. We updated our dashboard design in early October and along with it we addressed the sidebar and this should no longer be an issue.
