### ISSUE TITLE
Issue: Silent Failure When Creating Organization with Invalid Characters

### ISSUE THREAD

**Issue by Jemeni11** [polarsource/polar#3889]
### Steps to Reproduce:
1. Sign up with GitHub and navigate to the "Let's get started" page (https://polar.sh/dashboard/create).
2. Enter an organization name with apostrophes ("Emmanuel's Org").
3. Select all options in the section below.
4. Click "Create".

### Expected Behavior:
- User should receive immediate feedback about invalid characters in the organization name.
- Error message should be displayed on the page.

### Actual Behavior:
- The "Create" button becomes disabled without any visible feedback.
- No error message is shown on the page.
- Error is only visible in browser developer tools (Network and Console tabs).

### Error Details:
Console Error:
```
Failed to load resource: the server responded with a status of 422 ()
POST https://api.polar.sh/v1/organizations/ 422 (Unprocessable Content)
```

Network Tab Response:
```json
{
    "error": "RequestValidationError",
    "detail": [
        {
            "type": "value_error",
            "loc": [
                "body",
                "slug"
            ],
            "msg": "Value error, The slug can only contain ASCII letters, numbers and hyphens.",
            "input": "emmanuel's-org",
            "ctx": {
                "error": {}
            }
        }
    ]
}
```

### Suggested Improvement:
Add a validation message or error status display below the organization name input field to provide immediate feedback to users about invalid characters.

### Browser/OS Information:
Microsoft Edge 127.0.2651.98 (Official build) (64-bit) 
Windows 10 Version 22H2 (Build 19045.4651)

### Screenshots:

![422 error](https://github.com/user-attachments/assets/88ee46bb-61e4-4a7f-8e2c-88ea3e9aa997)
![network headers](https://github.com/user-attachments/assets/ff44e115-4f03-4e03-b8e9-3850b8682d82)
![network response](https://github.com/user-attachments/assets/7c89fc9d-493d-41db-a00e-a3da1b03dd34)

**Comment by frankie567** [comment]
Thank you for the super-detailed bug report, @Jemeni11. I'll take care of this rapidly 🙂

**Comment by frankie567** [comment]
The fix is live 👍 I improved the slug generation/validation on client's side so it matches server's expectations + it'll display the server error message in case something is wrong.
