### ISSUE TITLE
Private Organization Page by default

### ISSUE THREAD

**Issue by krzyzanowskim** [polarsource/polar#3893]
Hide (Private) the organization page by default, or make it an option. It's especially painful when combined with the missing delete organization feature https://github.com/polarsource/polar/issues/3892. Once created, public organization page is created and stays forever. Update/change organization handler is nice to have.

**Comment by birkjernstrom** [comment]
Great suggestion @krzyzanowskim and agree. We'll prioritize this one!

**Comment by emilwidlund** [comment]
@krzyzanowskim Public Page can now be disabled via the new Customize page in the dashboard :)
