### ISSUE TITLE
Ability to change Country while Payout Account status still "Onboarding incomplete"

### ISSUE THREAD

**Issue by codenoid** [polarsource/polar#3902]
Hi, congrats for the launch, so I was exploring Polar feature directly on the dashboard, but I was giving wrong value when I set-up an Payout Account, can we have feature to revert the the option? Thanks!

**Comment by birkjernstrom** [comment]
Closing this in favour of https://github.com/polarsource/polar/issues/3910 which would enable you to discard the incorrectly setup account and connect a new one. 

Reason being that we create payout accounts with third-parties (Stripe and soon others) and don't want to fiddle with them too much programatically for different reasons.
