### ISSUE TITLE
Add users to organization (user management)

### ISSUE THREAD

**Issue by mkurz** [polarsource/polar#3913]
Not 100% sure, but it seems currently if I create an organzation I can not add other users to the organization. Like I want to invite other users to manage the organization. On top of that it would be nice to assign permissions to these users (RBAC or similiar).

**Comment by birkjernstrom** [comment]
Thank you @mkurz. We support adding team admins, but don't expose a UI for it, i.e it needs to happen via support on our end. Definitely something we want to build a UI for instead. We have this discussion for the feature so closing this issue to avoid duplicates for now 🙏🏼
https://github.com/orgs/polarsource/discussions/3804
