### ISSUE TITLE
Product for 0,01$ creates checkout error

### ISSUE THREAD

**Issue by maxschulmeister** [polarsource/polar#3960]
The title says it, you can test it yourself [here](https://polar.sh/rectangle0/products/068d07d4-e58d-4631-b471-2caa6e141f88
)

For me clicking "Buy now" leads to _500 Internal Server Error_

**Comment by birkjernstrom** [comment]
Thank you @maxschulmeister. Missed the minimum requirement here from Stripe and only had validation for the maximum. Added a minimum validation now to match Stripe's requirement of `$0.5`

https://github.com/polarsource/polar/pull/3961
