### ISSUE TITLE
UI bug: Cannot create webhook as button is beyond viewport

### ISSUE THREAD

**Issue by wanjohiryan** [polarsource/polar#3975]
There is a bug on the UI when creating an webhook, the sheet is un-scrollable even when the button is beyond the viewport

![image](https://github.com/user-attachments/assets/35a14d7c-1afd-4852-830a-6accc68c469c)

**Comment by emilwidlund** [comment]
@wanjohiryan Thanks for the report! Deploying a fix as we speak.
