### ISSUE TITLE
Private note is required when creating Custom benefit

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#4005]
This should clearly be optional 🤔

**Comment by frankie567** [comment]
Currently, we use a single `BenefitCustomProperties` schema for both input and output. Problem is, the output has no default value, making it required.

We should introduce a `BenefitCustomCreateProperties`, like we already do for other benefits, where the `note` has a `None` default.

**Comment by nareshNishad** [comment]
@frankie567 i have raised the PR for the same https://github.com/polarsource/polar/pull/4099
