### ISSUE TITLE
Action required emails (GitHub/Discord invite) has missing variables

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#4007]
It looks like it doesn't have organization name or product name.

<img width="580" alt="Capture d’écran 2024-09-18 à 13 26 25" src="https://github.com/user-attachments/assets/e0df64aa-d7fe-4439-a45a-76ca020a7216">

**Comment by nareshNishad** [comment]
Hi @frankie567 how you want to handle, it either via fallback placeholder or error, let me know I can create a PR for this.

**Comment by frankie567** [comment]
Didn't check, but I think it's just a bug. I would like the actual values to be correctly shown 😄

**Comment by frankie567** [comment]
Those emails don't exist anymore now :)
