### ISSUE TITLE
Clicking on `Get Started` fails to reload anything.

### ISSUE THREAD

**Issue by apsinghdev** [polarsource/polar#4015]
In the development environment, when I click on the `Get started` button, nothing shows up on the screen. Ideally, there should be a page that we have in the production environment.

https://github.com/user-attachments/assets/f0596c61-3ce5-4cba-bb35-9e339aa7f90e

I would like to fix this if assigned.

**Comment by frankie567** [comment]
It's working well on my side on a local environment. There is probably an error in the console where you'll find clues about what's happening.

Side note: we tend to always use `127.0.0.1` instead of `localhost` while developing. From our experience, it avoids lot of headaches.
