### ISSUE TITLE
sandbox issues to create test product

### ISSUE THREAD

**Issue by artivilla** [polarsource/polar#4040]
Noticed 2 issues:
- The sandbox image upload doesn't render. Same image is used in prod in my account and works great.
url: https://sandbox.polar.sh/dashboard/print-shop-dev/storefront
- Clicking on the sandbox product hits a 404

<img width="1824" alt="image" src="https://github.com/user-attachments/assets/e1b38dc8-2f61-43f8-aaa1-cb175a69e0a0">

<img width="1824" alt="image" src="https://github.com/user-attachments/assets/64b5d05e-461a-4912-8041-1787935386d0">

**Comment by frankie567** [comment]
Thank you for reporting @artivilla 👍 There was a missing configuration on our sandbox S3 bucket that prevented images from being read. That's now solved!

Regarding the 404 on the product page, I see that your `print-shop-dev` organization has not enabled the storefront; meaning products are not accessible through Polar. You can enable it by going to `Storefront` and enable the toggle on the right:

<img width="398" alt="Capture d’écran 2024-09-23 à 15 15 38" src="https://github.com/user-attachments/assets/b65146e5-6207-4558-8ed4-8ca65d6d7d80">

**Comment by artivilla** [comment]
oh interesting. feel like we should add some sort of messaging on the page to active the storefront. wasn't obvious.
