### ISSUE TITLE
personal access token selection items not scrollable

### ISSUE THREAD

**Issue by artivilla** [polarsource/polar#4064]
When I open the list to view selections for personal access token, it renders outside the viewport. Likely needs to be wrapped in some scrollable view.

<img width="1840" alt="image" src="https://github.com/user-attachments/assets/ca9c013b-6207-4363-a7ba-350857a60494">

**Comment by birkjernstrom** [comment]
Sorry for missing & responding to this one @artivilla. 

We've fixed this issue a while ago so the dialogue is smaller & scrollable ♥️ Thank you for reporting it.
