### ISSUE TITLE
Add option to set success_url when creating a checkout link

### ISSUE THREAD

**Issue by emilwidlund** [polarsource/polar#4095]
When copying a checkout URL from the product, it isn't possible to set a success_url.

We should make the "Copy Checkout URL" open a modal instead, where you can optionally set a success url, and select which price you want to generate the link for.

**Comment by frankie567** [comment]
Interesting! But this will require a dedicated object (like Stripe's PaymentLink) to make it work securely. We can't let checkout link arbitrarily set success URL (it would open up security issues with malicious users impersonating websites).

~1 week work.
