### ISSUE TITLE
Implement a SVG badge for single product 

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#4098]
Would be ideal to feature a specific product on a README; with a direct link to checkout.

---

I would then deprecate the tiers badge, which makes less sense with our new focus

**Comment by birkjernstrom** [comment]
I'll deploy this tomorrow :-) Got it working on Friday. Just need to fix the design, but been in meetings all day today

**Comment by birkjernstrom** [comment]
Deployed earlier this week, but forgot to close :-)
