### ISSUE TITLE
Syntax error in the `POLAR_ALLOWED_HOSTS ` var of the `.env.template` file.

### ISSUE THREAD

**Issue by apsinghdev** [polarsource/polar#4100]
There is a minor syntax error in the `POLAR_ALLOWED_HOSTS ` var of the `.env.template` file.

Current Behaviour

`POLAR_ALLOWED_HOSTS=["localhost:3000", "127.0.0.1:3000"]`

Ideal Behaviour

`POLAR_ALLOWED_HOSTS='["localhost:3000", "127.0.0.1:3000"]'`

Screenshot

<img width="765" alt="Screenshot 2024-10-06 at 12 26 56 PM" src="https://github.com/user-attachments/assets/1f0ce8b4-9716-4376-92d1-ff0d23be7ebd">

**Comment by frankie567** [comment]
Good catch! Feel free to open a PR about it 👍

**Comment by apsinghdev** [comment]
> Good catch! Feel free to open a PR about it 👍

Thanks! Opened the PR.
