### ISSUE TITLE
Checkout: Toggle VAT number field

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4130]
We should default to having it hidden with a link `Add Tax ID` that would show it and `X` to close it once open. Making the checkout form immediately feel more lightweight (higher conversion) vs. having it open for everyone even though it's only applicable for businesses.

**Comment by malisettisamrat** [comment]
<img width="592" alt="Screenshot 2024-10-16 at 8 53 19 AM" src="https://github.com/user-attachments/assets/e135fc23-ce61-42a9-b6ba-d9db7e930674">

Hello @birkjernstrom, you want to show this Tax ID as a link and shows up when we try to click on it?

**Comment by apsinghdev** [comment]
@birkjernstrom does this look good?

https://github.com/user-attachments/assets/0ebb8994-d5f6-43bf-87f1-17939141fe48
