### ISSUE TITLE
Subscription lifecycle webhooks

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4168]
Currently, we offer `subscription.created` and `subscription.updated`. Latter is fine to capture all update events. However, developers need to compare state themselves to determine the lifecycle event, e.g `renewed`, `cancelled` etc.

In addition to `subscription.updated` (catch-all) we should introduce more specific events to subscribe to. Naming is not written in stone, but rather illustrative below.

- [ ] `subscription.cancelled`
- [ ] `subscription.expired`
- [ ] `subscription.payment_succeeded`
- [ ] `subscription.payment_failed`
- [ ] `subscription.payment_recovered`

**Comment by frankie567** [comment]
Interesting! I would suggest to mirror the different states we receive from Stripe: https://docs.stripe.com/api/subscriptions/object#subscription_object-status

Pros:

* We already capture that status when receiving Stripe webhooks
* Don't need to add logic on the Order side

**Comment by frankie567** [comment]
So, here is what I'm envisioning:

* [ ] `subscription.active`
    * ➡️ Access should be granted, either because it's a new one that has been successfully paid or because failed payments were settled
    * Interesting to have besides `subscription.created` because, at creation, the initial payment **may not** have been fully processed (the subscription is in `incomplete` state)
* [ ] `subscription.canceled`
    * ➡️ The customer canceled the subscription. They might keep access until the end of the billing period. Until then, benefits remain active.
* [ ] `subscription.revoked` 
    * ➡️ Access should be revoked. Underneath, the status could be `canceled` (user canceled the subscription), `past_due` (latest payment failed but we'll retry) and `unpaid` (all payment attempts failed).
    * ➡️ It mirrors our behavior around benefits: when we are in those states, benefits are revoked.

---

To track renewals, we already have `order.created` which should cover the use case. The `Order` object has a `subscription` property which help identify the corresponding subscription.
