### ISSUE TITLE
Landing: The word "Testamonials" is misspelled

### ISSUE THREAD

**Issue by reynaldichernando** [polarsource/polar#4221]
### Description

There are typos in the word “Testimonials” in these 2 files. 

https://github.com/polarsource/polar/blob/73a4db9dec9f1344f7b0f0b72f83db41db755c1a/clients/apps/web/src/components/Landing/Testamonials.tsx#L81

https://github.com/polarsource/polar/blob/73a4db9dec9f1344f7b0f0b72f83db41db755c1a/clients/apps/web/src/components/Landing/LandingPage.tsx#L4

### Current Behavior
The words are currently written as “Testamonials”.
Note that these typos are only in code and not user facing, since there is no mention of “Testimonials” in the landing page.

### Expected Behavior
They should be “Testimonials”.

### Screenshots

None, these typos are not user facing, it is only in the code.

### Environment:

-   Operating System: -
-   Browser (if applicable): -

---

**Comment by reynaldichernando** [comment]
The fix should be fairly straightforward, simply by updating the component name and the variable names in the code.
I would love to submit a PR for this!

**Comment by apsinghdev** [comment]
@reynaldichernando are you working on it?

**Comment by reynaldichernando** [comment]
Yes @apsinghdev

**Comment by apsinghdev** [comment]
> Yes @apsinghdev

great!
