### ISSUE TITLE
Not showing `pending` grants anymore in order details page

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4236]
## Description

Our new order details page no longer shows `pending` grants which can be the case for Discord & GitHub benefits where the user has received an email & nudge to connect their account, but have not done so yet. Before we used to show the benefit and nudged them to connect their account on this page too. That is required in order for the benefit to be fully granted, i.e a GitHub/Discord invite to be completed.

This causes a UX issue where the user believes they have not received the benefit until they first check their email & complete the steps there.

## Replicate

1. Create a product with GitHub/Discord benefit
2. Buy product from a user without GitHub/Discord connected
3. You won't see the GitHub/Discord benefit in your orders detail page anymore since it hasn't been fully granted yet. We used to show it along with a nudge to connect GitHub/Discord directly on the page for the user.

**Comment by frankie567** [comment]
Not applicable anymore
