### ISSUE TITLE
Docs homepage always shows in dark mode even if light mode is set

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#4299]
### Description

Reported by our friends at Speakeasy: the homepage of our docs always use dark mode, even if the device is in light mode; which is weird when going to another page.

### Current Behavior

Docs homepage is always in dark mode

### Expected Behavior

Docs homepage should adapt to the light/dark mode of the device

### Screenshots

https://github.com/user-attachments/assets/5a4f56ce-43b1-4e9e-b1dc-dda184f12970

### Environment:

-   Operating System: *
-   Browser (if applicable): *

---

**Comment by reynaldichernando** [comment]
I think we could have `useTheme('system')` on the docs page.
https://github.com/pacocoursey/next-themes?tab=readme-ov-file#usetheme-1

But this would be a double override 🤔 (in provider we override the theme, then in the page we override the theme again)

I was thinking instead, maybe there is no pages with forced dark theme on the provider level, but each page that needs dark theme will call the `useTheme` or just set the theme property (https://github.com/pacocoursey/next-themes?tab=readme-ov-file#force-page-to-a-theme).

**Comment by frankie567** [comment]
Not an issue anymore since we re-added light mode support on landing pages
