### ISSUE TITLE
Chrome Extension: Redirect to login with `goto_url` in case user is unauthenticated

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#430]
<img width="1552" alt="Screenshot 2023-05-16 at 13 46 21" src="https://github.com/polarsource/polar/assets/281715/cddc85b1-8023-4a0f-949a-401c96764457">

**Issue**
Chrome Extension prompts to connect, e.g "Connect Polar", which assumes an authenticated user. In case I'm not, I'm redirected to the extensions page which receives a 401 and hangs in the "One second, establishing connection...". Since we have `goto_url` now, we should have an error handler on 401 that redirects to login with itself as the `goto_url` which should resolve the issue.

**Comment by hult** [comment]
Probably also fixes #242?
