### ISSUE TITLE
Make product description optional

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4373]
### Description
<img width="884" alt="image" src="https://github.com/user-attachments/assets/fb5a5034-25f4-4252-919d-1b75d3f9b2f0">

Currently, we require a description for products. It made sense historically, but given our API-first/integration approach these days it's better to leave optional for the creator.

### Current Behavior

- Form validation error upon creating a product without a description

### Expected Behavior

- Ability to create a product without a description – no errors.

**Comment by birkjernstrom** [comment]
Yes @Tayamul we greatly appreciate contributions.

This would also require changes to our API/backend in Python to make it an optional value. Looking at your profile I see Node/TS/JS, but do you feel comfortable with Python too?

**Comment by Tayamul** [comment]
Although I've only dabbled in Python before, I'm confident I can make the changes, as I'm currently a backend developer and the fix should be straightforward.

**Comment by naineel1209** [comment]
Hi @birkjernstrom, sorry for jumping in between the discussion,

> This would also require changes to our API/backend in Python to make it an optional value.

But based on the [documentation for the server endpoint](https://docs.polar.sh/api/v1/products/post), it appears that the `description` property is already marked as optional. Therefore, only frontend changes might be needed. If that's the case, I've already implemented the necessary changes on the frontend. Is that correct?

**Comment by birkjernstrom** [comment]
Re: Above. It's super strange, but another user claims to already have a patch up and running and the above was in response to him over email. I've never experienced this before where the conversation online is not reflective of a users direct message over email; I can only assume it means no account exists for that user and that they can still chat over email...

@Tayamul Wait given the above to avoid any unnecessary work. Potentially, it might be in progress already, but otherwise it's yours + above you have context that in this case no Python/backend is necessary even. Just a change on the frontend validation.

**Comment by naineel1209** [comment]
Hi @birkjernstrom, I apologize for the confusion, but it looks like my previous message was accidentally deleted before it could be posted in the discussion. However, you might have received it via email.

I'm referencing it below:
```md
Hi @/birkjernstrom, Sorry for jumping into the discussion.

> This change would also require modifications to our API/backend in Python to make it an optional value. 

However, based on the documentation for the server endpoint (https://docs.polar.sh/api/v1/products/post), it appears that the description property is already marked as optional. Therefore, only frontend changes might be needed. If that’s the case, I've already implemented the necessary changes on the frontend. Is that correct?
```
