### ISSUE TITLE
DX: Checkout & Checkout Link API to accept `product_id` too vs. `product_price_id` only

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4374]
### Description

Support *either* `product_price_id` or `product_id` in the following endpoints.
- `POST /v1/checkouts/custom/`
- `POST /v1/checkout-links/`

In case `product_id` is provided, the endpoints should default to the currently active `product_price_id` and first one in case of multiple (subscriptions, e.g monthly or annual).

### Current Behavior

Today, we require a `product_price_id`. However, in most cases `product_id` is more intuitive in addition to being automatically updated to the most recent price in case of changes in the dashboard. We still want to support the latter for historic reasons + for customers seeking more advanced use cases and being more explicit.

### Expected Behavior

1. I can create a checkout session `POST /v1/checkouts/custom/` with `product_id` instead of `product_price_id` and it will automatically use the active price for the session
2. I can create a checkout link `POST /v1/checkout-links/` with `product_id` instead of `product_price_id` and upon going to the generated link I'm presented with a checkout reflecting the active price
3. I can change the price of the product and 1) run the same checkout API request and get the latest price & 2) use the old checkout link and come to the checkout with an updated price

**Comment by magarpratik** [comment]
Hi, I’d love to work on this issue if it's available. I can look at this next week.

If that's okay, could you please assign it to me? 
Thanks!

**Comment by birkjernstrom** [comment]
Absolutely @magarpratik - really appreciate it! We don't assign issues unless a core team member is actively working on it. We've found that the comments here + activity of potential PRs (including drafts) etc are sufficient otherwise to avoid race conditions of contributions. Otherwise, in case things come up (school, work, life, other priorities etc) that prevent contributions from happening (understandable & fine) the assignment becomes stale and has a negative effect. Hope that makes sense?

Join our Discord too if you want and we'd be happy to help with this contribution with any questions or problems you run into.
https://dub.sh/polar-discord

**Comment by birkjernstrom** [comment]
Strange. Just checked and the invite code is active & should work. Could you try again? Otherwise, try this:
https://discord.gg/BZw96tszTX

**Comment by magarpratik** [comment]
That worked. Thanks!

**Comment by birkjernstrom** [comment]
Unfortunately, @magarpratik I'll need to work on & ship this one sooner to fix feedback/confusion for customers. However, I'm separately working on updating/improving our backlog and am confident we'll have plenty of good issues to sink your teeth into if you're interested :-) Feel free to DM me on our Discord and we can discuss good issues.

**Comment by magarpratik** [comment]
That's completely fine @birkjernstrom 👍

I am planning to work on [this issue](https://github.com/polarsource/polar/issues/4396) for now, so that should keep me busy for a while.
