### ISSUE TITLE
Dashboard: Better cold start & empty states

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#444]
Currently, our dashboard is built for the happy path of having issues and dependencies. Below are cases and how we should deal with them.

**Backers without connected repositories**
- [ ] Don't show "Issues | Dependencies" tab since they can only have dependencies, i.e issues they pledge toward

_Note:_ We shouldn't remove this tab based on issue and dependency count, but rather a boolean flag on the organization, e.g `has_repos` – in case there are connected repositories we should always show the filter tab.

@petterheterjag Let's quickly align on the "empty state" design for each state below.

**No issues: Matching filters**
- [ ] Remove issue count + sorting navigation
- [ ] Showcase empty state for no issues matching given filters

**No issues: Matching search**
- [ ] Remove issue count + sorting navigation
- [ ] Showcase empty state, e.g "No issues matching <search query>"

**No dependencies**
- [ ] Remove issue count + sorting navigation
- [ ] Showcase empty state. Use this opportunity to educate how Polar works, i.e references in internal issues showing up as dependencies

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/444">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/444/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/444/pledge.svg">
</picture>
</a>

**Comment by petterheterjag** [comment]
Design for no dependencies: https://www.figma.com/file/XyFpx0vdHk6bfWYLWmOHSC/Polar-Mega-File?type=design&node-id=2951-77705&mode=design&t=shEUDqMVcBXElg9h-4
