### ISSUE TITLE
Ops: Add worker health to status page

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4464]
We should add our worker to our public status page.

**Challenge**
Our worker is not accessible publicly, i.e cannot offer a health endpoint directly.

**Solution**
- Setup a scheduled task, e.g each minute, for the worker to store some checks in Redis. 
- Add a `/healthz` endpoint to our public API checking the above and reporting `200` or `500` accordingly

**Comment by frankie567** [comment]
Discovered this: 

* https://arq-docs.helpmanual.io/#health-checks
* https://github.com/python-arq/arq/blob/3914e48c530f0e5acf02cb340b1f8f3e201ba895/arq/worker.py#L891-L919

ARQ already writes its own healthcheck key in Redis; so maybe we just need to query for that key in our health endpoint.

**Comment by naineel1209** [comment]
Hi @birkjernstrom, I've created a PR with the changes mentioned in the discussions. Could you please check it?
