### ISSUE TITLE
Dashboard: General Toast

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#447]
Allowing us to better inform users about errors or successful actions that have taken place

**Comment by petterheterjag** [comment]
Opinions on using https://github.com/timolins/react-hot-toast for this? I used it for Editeur and thought it was nice.

**Comment by birkjernstrom** [comment]
I love that we use as much OSS as possible so fully supportive.

I also saw this one a few weeks ago which is really nice and potentially with more options? Nice bonus: Leverages Radix UI + Tailwind so fits well.

But trust & back your decision on what's most suitable from a design POV

**Comment by birkjernstrom** [comment]
Forgot to link: https://ui.shadcn.com/docs/components/toast

**Comment by petterheterjag** [comment]
That seems like a better option 👍
