### ISSUE TITLE
Discounts

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4473]
### Discussed in https://github.com/orgs/polarsource/discussions/3937

Ability to create coupon codes.

- Discounts being a % or fixed ($) amount
- Offered as coupon codes vs. automatically enabled (future enhancement)
- Across entire organization or for select products
- Usage limitations
- Settings on how to apply them for subscriptions
- Ability to create/set them when creating a checkout session
- Ability to set them in a checkout link using above + obfuscating the code itself behind the checkout link

**Comment by frankie567** [comment]
This is now deployed in production 🎉

@sindresorhus Regarding what you suggested we have two ways for presetting a discount on a checkout link:

- At link creation, you can preset a discount. It'll be automatically applied on the checkout session. There is also a parameter to hide the discount code input.
- Through the `discount_code` query parameter on the link itself, allowing you to prefill the discount code input.
