### ISSUE TITLE
Custom Fields: Improve how long input (messages) is shown in order details 

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4547]
### Description

Easy to miss the entire content of long strings in custom fields on order details.

### Current Behavior

Long messages/strings in custom fields are cut in the order details – requiring hover to show the full contents. 

### Expected Behavior

Experiment with the more user friendly option & design:
1. Truncate string after X characters followed by `... (Show more)` 
2. Show in `<textarea disabled>` with a somewhat decent default size, but ability to scroll within textarea 

### Screenshots

![image](https://github.com/user-attachments/assets/41c18fcb-fff8-4bc8-9c2a-018129758f33)

**Comment by plugisto** [comment]
Just an idea: when this is customer facing you should also remove the label "Custom Fields". I believe it's confusing (or just not relevant in the best case). "Custom Fields" as a label is of no interest for them - they don't care how things are called inside of Polar. IMHO you should just remove it. Keep the single label + value and that's fine. Nothing else needed.

**Comment by frankie567** [comment]
To my defence, this was designed to be displayed in the table, not in a modal with plenty of space 😅

**Comment by birkjernstrom** [comment]
> Just an idea: when this is customer facing you should also remove the label "Custom Fields". I believe it's confusing (or just not relevant in the best case). "Custom Fields" as a label is of no interest for them - they don't care how things are called inside of Polar. IMHO you should just remove it. Keep the single label + value and that's fine. Nothing else needed.

Just to clarify the screenshot is from the dashboard and what the developer/seller sees and not the end customer. They only see the field on checkout as an input like the others.

I still hear you though, but I think it's less obvious to not distinguish them since the feature is `Custom Fields` that the developer can setup themselves. That said, they'll recognize that and perhaps we can distinguish it more with an icon / link to edit the custom field or equivalent vs. the title.

**Comment by magarpratik** [comment]
Hi @birkjernstrom, it seems the described functionality is already implemented - unless I'm misunderstanding the issue?

https://github.com/user-attachments/assets/d203aa42-7f82-4f18-8bf3-f030b796a0d0

The dummy data used in the above recording can be found in [this commit](https://github.com/magarpratik/polar/commit/89cec37b0d044c6407dc96439441e6304d4d8a2d).
