### ISSUE TITLE
Tax: Move setting to products vs. benefits alone

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4613]
### Description

Streamline tax settings on a product vs. benefit-level. Avoiding confusion and corrections currently needed in our manual account reviews. 
 
### Current Behavior

We've set tax applicability/settings on a benefit vs. product level. It made sense earlier in the year when we only offered subscriptions and to an audience that always setup our automated benefits. However, as we grow, some customers launch products without any benefits. Creating unnecessary risk on our side and confusion for customers.

### Expected Behavior

You set tax settings on the product vs. benefits-only.
- Default: On
- Required in case tax applicable benefits are enabled

**Comment by frankie567** [comment]
After internal discussions, here is our final plan:

* Add `is_tax_applicable` to the `Product` model.
* For past and new products, always set it to `True`, unless it's a migrated *Donation* product (identifiable by `{"donation_product": true}` in `user_metadata`).
* Users can't turn this setting off. If they want to disable tax, they should reach our support so we can manually review if their use-case is applicable to tax exemption.
