### ISSUE TITLE
Cannot generate PAT token from dashboard or sandbox

### ISSUE THREAD

**Issue by salvinoto** [polarsource/polar#4615]
### Description

On the Sandbox dashboard, I am unable to generate a PAT token.

### Current Behavior

When filling out the form and pressing generate, nothing happens and console shows a vague error.

### Expected Behavior

I should be able to get a PAT token

### Environment:

MacOS, Zen Browser

---

**Comment by ojaydev** [comment]
same here, I can't generate a token in both environments.

**Comment by ojaydev** [comment]
> same here, I can't generate a token in both environments.

actually just found a temp fix, don't select all scopes, just use the ones you need, I think there's an issue with one or more scopes, that's why it's not generating the keys.

**Comment by birkjernstrom** [comment]
Sorry, I can't believe I missed this notification. Will prioritize this ASAP and ship a fix quickly.

**Comment by birkjernstrom** [comment]
Deployed a fix along with overhauling the entire form into an `InlineModal` for a better experience, error handling and more. Thank you for reporting this @salvinoto & @ojaydev and apologies again for missing the notification in the first place 🤦🏼‍♂️
