### ISSUE TITLE
PAT: Show error message if scope+expiration is not set

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4616]
You can click `Create` for a new Personal Access Token (PAT) under `/settings` without having set at least 1 scope or an expiration.

However, this will not trigger anything until a scope and expiration is set since those are required. Creating confusion for the user.

**Solution**
- Disable `Create` until all fields are set
- Add downward arrow in `Select scope` component to mimic a typical select to better indicate selection
- Change `Expiration` to `Set expiration` to better indicate a selection required

**Comment by Tayamul** [comment]
I’d be happy to take on this issue.

**Comment by birkjernstrom** [comment]
Sorry @Tayamul I had to fix a bug in the form and took the opportunity to move it into an InlineModal and could then quickly fix all of the issues here in the same go. But we'll be adding a lot more `contributor friendly` issues in the near future too :)
