### ISSUE TITLE
Remember last organization when opening dashboard

### ISSUE THREAD

**Issue by qwtel** [polarsource/polar#4619]
### Description

Opening a fresh browser tab with the polar.sh dashboard should show the most relevant organization if there is more than one.

### Current Behavior

Currently it redirects to the first organization in the dropdown list, which is the most recently created one.

### Expected Behavior

Redirect to the organization that was most recently manually selected from the dropdown list, or some other metric like revenue, etc.

### Environment:

-   Operating System: [e.g., Windows, macOS, Linux]
-   Browser (if applicable): [e.g., Chrome, Firefox, Safari]

---

**Comment by magarpratik** [comment]
I am working on this issue 👍

**Comment by qwtel** [comment]
Thanks for shipping this. Happy about this every time I open polar.sh in a new tab 😃
