### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by kiongosss** [polarsource/polar#4623]
500: INTERNAL_SERVER_ERROR
Code: EDGE_FUNCTION_INVOCATION_FAILED
ID: cpt1::q44vj-1733896278852-5d2eb0528353

**Comment by birkjernstrom** [comment]
I'll email you @kiongosss since I know why this is happening, but expected and I'll share more personal context over email.

**Comment by kiongosss** [comment]
> I'll email you @kiongosss since I know why this is happening, but expected and I'll share more personal context over email.

Duly noted.
