### ISSUE TITLE
Email validation logic during pre-filling checkout metadata too strict

### ISSUE THREAD

**Issue by samuelandert** [polarsource/polar#4625]
### Description

Email validation during checkout creation is too strict, causing valid email addresses to be rejected. This occurs during the checkout process when attempting to create a new checkout with a customer email address.

### Current Behavior

The email validation is performing a too strict behaviour, which causes issues with valid but new or uncommon domain names. For example, emails with the domain "visionscreator.earth" are being rejected with the error:

```
dev: Error creating Polar checkout: HTTPValidationError: API error occurred: {"detail":[{"loc":["body","CheckoutProductCreate","customer_email"],"msg":"value is not a valid email address: The domain name visionscreator.earth does not exist.","type":"value_error"},{"loc":["body","CheckoutProductCreate","product_id"],"msg":"Field required","type":"missing"},{"loc":["body","CheckoutPriceCreate","customer_email"],"msg":"value is not a valid email address: The domain name visionscreator.earth does not exist.","type":"value_error"}]}
api:dev:   'data$': { detail: [ [Object], [Object], [Object] ] },
api:dev:   detail: [
api:dev:     {
api:dev:       loc: [Array],
api:dev:       msg: 'value is not a valid email address: The domain name visionscreator.earth does not exist.',
api:dev:       type: 'value_error'
api:dev:     },
api:dev:     { loc: [Array], msg: 'Field required', type: 'missing' },
api:dev:     {
api:dev:       loc: [Array],
api:dev:       msg: 'value is not a valid email address: The domain name visionscreator.earth does not exist.',
api:dev:       type: 'value_error'
api:dev:     }
api:dev:   ]
api:dev: }
```

### Expected Behavior

Email validation should:
- Allow new or uncommon TLDs

### Environment:
- polar-sdk, when trying to pre-fill a new checkout with exotic mail domain addresses.

**Comment by frankie567** [comment]
Hey @samuelandert 👋 

We're not rejecting domains based on their TLD. Under the hood, there is actually a DNS check to make sure there are MX records for that domain (in the case of `visionscreator.earth`, [there are indeed none](https://www.whatsmydns.net/#MX/visionscreator.earth)).

In my humble opinion, this is an important feature for us to avoid:

1. Typos like `john@gmal.com`
2. Fake email addresses, which might cause compliance issues if we need to reach out for the customer.

@birkjernstrom, what are your thoughts on this?

**Comment by samuelandert** [comment]
Hey @frankie567, thanks a lot to look into this.
I have to take this one back. I indeed made that typo mistake, well done on your validation there! 
The correct domain is visioncreator.earth instead of vision(s)creator.earth, so all good!
