### ISSUE TITLE
Docs: Some pages return `404` if user is not logged in

### ISSUE THREAD

**Issue by magarpratik** [polarsource/polar#4637]
### Description

When a user is not logged in and attempts to access the following pages, they receive a `404` response.

<img width="750" alt="Screenshot 2024-12-15 at 17 03 26" src="https://github.com/user-attachments/assets/73161016-9741-4b25-bf94-778582a58489" />

#### 404 response

<img width="350" alt="Screenshot 2024-12-15 at 17 06 12" src="https://github.com/user-attachments/assets/81641748-5d3e-4df0-9bb9-43e7d334eb24" />

### Current Behavior

Users who are not logged in are unable to access some documentation pages.

### Expected Behavior

Users should be able to access all documentation pages without the need to log in.

### Screen recording

https://github.com/user-attachments/assets/c15bcc09-7bc8-4b5c-a32d-d52ee1538757

### Environment:

-   Operating System: macOS
-   Browser: Brave browser

**Comment by birkjernstrom** [comment]
Can confirm 😬 Will fix ASAP
