### ISSUE TITLE
PAT: Cannot create with all scopes

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#4638]
Cannot create a PAT with all scopes (production & sandbox). No request is made and no error message shown.

Reducing scopes does not work either. Until the name is changed and then it's possible.

So quite a buggy experience. Need to prioritize.

**Comment by magarpratik** [comment]
Is this a duplicate of #4615 ?

**Comment by birkjernstrom** [comment]
Yes 🤦🏼‍♂️ Can't believe I missed that notification. Bad bug. Closing this one and will prioritize the other issue ASAP.
