### ISSUE TITLE
Progressive Onboarding: Chrome Extension – remove upsell post install/skip

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#465]
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/465">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/465/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/465/pledge.svg">
</picture>
</a>

**Comment by hult** [comment]
This seems like it's already fixed, right, @zegl?
