### ISSUE TITLE
Checkout page stuck loading at Free plan

### ISSUE THREAD

**Issue by duylddev** [polarsource/polar#4674]
### Description

- I have 2 plans in Polar.sh, 1 is free plan
- Checkout works fine with paid plan. But in free plan, it keep loading (email is received and plan is activated in dashboard)
- 
### Current Behavior
- it keeps loading and doesn't redirect

### Expected Behavior
- Redirect to config url

### Screenshots
<img width="595" alt="image" src="https://github.com/user-attachments/assets/7937559b-856c-4402-bfc8-0e19e198930b" />
### Environment:
-   Browser (if applicable): [Chrome Desktop]

---

**Comment by frankie567** [comment]
Thank you for the report @duylddev! I can confirm this behavior when a success URL is set. Will fix it ASAP.
