### ISSUE TITLE
Cannot mark issue is not solved but closed/reject funding

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#4729]
### Description

An issue was not solved but closed.
How do I mark that? 

### Current Behavior

I can only mark the issue as done and pay it out.

![grafik](https://github.com/user-attachments/assets/b3889c3f-1328-41a6-bdab-a54a6116c9bd)

### Expected Behavior

Nobody worked on this. How can I reject the funding?

![grafik](https://github.com/user-attachments/assets/0561d7e9-7ffd-402b-b73d-a2f20f0760b9)

### Environment:

-   Operating System: [e.g., Windows, macOS, Linux] Linux
-   Browser (if applicable): [e.g., Chrome, Firefox, Safari] Firefox

---

**Comment by birkjernstrom** [comment]
We don't support that in the UI and issue funding as a feature is currently in maintenance mode at Polar. Reach out to me via support and I can help refund it (support@polar.sh)
