### ISSUE TITLE
Improve upsell cards

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#535]
Unnecessarily large at the moment. I think we can reduce their height (~50% at least) and also tighten up the copy accordingly. Making them feel more like a power-up vs. forced and boring step.

**Comment by petterheterjag** [comment]
The design has been tighten up now: https://github.com/polarsource/polar/pull/599
I also tweaked the copy slightly, but I still feel that one of the cards have too much text. Maybe something you can tackle when you have time @birkjernstrom?

**Comment by birkjernstrom** [comment]
Awesome @petterheterjag ! Agreed – updated copy now in https://github.com/polarsource/polar/pull/608
