### ISSUE TITLE
Badge: Align with text

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#539]
<img width="928" alt="image" src="https://github.com/polarsource/polar/assets/281715/b43ef2ec-a6e1-4363-a49d-3132311c2237">

SVG from Satori has a padding causing our badge to be a bit indented from the text which is visually annoying. Let's reset some `body` padding or whatever is causing this

**Comment by zegl** [comment]
This comes from a bit of a flaw in our setup. Our usage of boxShadow is incompatible with a 0px-margin, and that the SVG effectively has `overflow: hidden` when rendered.

Setting the margin to 0 will align the box with the text, but it will clip the shadow. 

I have a little demo page for working with the SVG, and here is what this would look like:

<img width="1499" alt="Screenshot 2023-05-24 at 09 44 22" src="https://github.com/polarsource/polar/assets/47952/176b3d19-50c8-4134-973d-30638408f1bf">

Maybe using a non-shadow border would be a good compromise?

<img width="1499" alt="Screenshot 2023-05-24 at 09 44 16" src="https://github.com/polarsource/polar/assets/47952/e8a8ed55-956c-41f9-b56a-9329ac96c905">

**Comment by petterheterjag** [comment]
It probably makes sense to remove the shadow. What do you think @birkjernstrom?

**Comment by birkjernstrom** [comment]
Thanks @zegl for the excellent (+interesting) context!

I agree. Alignment is more important than the shadow and the badge does still look nice without it. Just not as nice. Given the importance of the badge (for all parties), I'd therefore like to do an attempt of:

- Create a realistic example in Storybook of an issue with real text and the badge. Showcasing the alignment issue.
- We can experiment quickly with shadow, but offsetted perhaps to avoid any on the lefthand side. If not, we go with borders.

**Comment by birkjernstrom** [comment]
@petterheterjag I think you can probably visualize this in your "minds eye". So do let me know if you can already tell that wouldn't work and look horrendous :) Otherwise, I'd love to experiment 15-20 min on this to absolutely nail the final result.

**Comment by petterheterjag** [comment]
hmm, we could perhaps do a very short/subtle shadow that just spreads vertically. let me test that :)

**Comment by petterheterjag** [comment]
I think that would work!
<img width="877" alt="Screenshot 2023-05-24 at 11 06 16" src="https://github.com/polarsource/polar/assets/1426460/b4850351-ec64-4f5d-9698-5c91291eb862">

**Comment by zegl** [comment]
> Create a realistic example in Storybook of an issue with real text and the badge. Showcasing the alignment issue.

I've added one in #545!

**Comment by petterheterjag** [comment]
Here's a PR that implements my suggestion above: https://github.com/polarsource/polar/pull/553. The shadow is now more subtle, but I think that's kind of nice.
