### ISSUE TITLE
Adding standard API error response

### ISSUE THREAD

**Issue by sultaniman** [polarsource/polar#556]
@zegl @hult @birkjernstrom I was wondering if defining common API error schema is a good idea?
Something like

```py
class APIError(BaseModel):
    code: ErrorCode
    status_code: int
    message: str
    data: Any
```

And for `ErrorCode` 

```py
class ErrorCode(str, Enum):
    unauthorized = "unauthorized"
    forbidden = "forbidden"
    not_found = "not_found"
    conflict_error = "conflict_error"
    totp_error = "totp_error"
```

**Comment by birkjernstrom** [comment]
Hey @sultaniman 👋🏼 Awesome to see your contributions (will review PR tomorrow) and suggestions! 🙏🏼

We've been emphasizing to move fast toward launch and thereafter be able to iterate quickly to help maintainers get more funding. Our "private" API design has therefore taken a bit of a backseat at this stage tbh.

Ideally in the future, I think we should have a standardized payload for the entire API for easier client-side integration. E.g having `response.ok` determine successful response vs. HTTP status codes and `response.data` on success or  `response.error`. Or even JSON-API. 

In the meantime, I think having standard error responses is great. However, I think that is `HTTPException` in our case at this stage and that an exception is preferable to a custom Pydantic model. Allowing us to raise errors – cleaner code and clearer intent. In case we need more than `status_code` and `detail`, I think we can have our own subclass of `HTTPException`, but I think we can save that to when there is a clear use case.

With that said: Curious to get your feedback if there is a use case you have in mind?

**Comment by sultaniman** [comment]
Cool, sounds fair :)
