### ISSUE TITLE
Better error handling of pledges

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#584]
Currently, it's happy path with `paymentIntent.status === succeeded`. For a great user experience we need to test and support all types of error flows exceptionally well.

https://stripe.com/docs/payments/intents#intent-statuses

**Comment by hult** [comment]
The only ones we don't handle is (as far as I can make out) `requires_confirmation` (optional, we don't need it), `requires_action` (do we have 3d secure enabled?), and `canceled` (but we never cancel intents, and I don't see when we could).

If we add payment methods other than cards, I guess there could be a point in treating `processing` different from `succeeded`?
