### ISSUE TITLE
Duplicate notification on pledge received

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#611]
<img width="460" alt="image" src="https://github.com/polarsource/polar/assets/281715/c7a2d841-aa57-4ca0-9c82-14ccf6eed929">

**Comment by zegl** [comment]
Seems like this is a copy bug on the frontend, and a result of you pledging to yourself (double pledge pending notifications).

The notifications sent to you are:

- PledgerPledgePendingNotification (the first one, with buggy copy)
- MaintainerPledgePendingNotification
- MaintainerPledgeCreatedNotification
