### ISSUE TITLE
Badge not embedded despite `polar` label added on one particular repo

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#628]
Specifically https://github.com/anthonycorletti/cloudrun-fastapi issue nr. 5. Not doing a direct link to avoid cluttering their timeline with this (not relevant).

**Comment by zegl** [comment]
I'm unable to reproduce this. I've added more logs (in #629) to have more data to use if this happens again.

Closing this issue for now, let's re-open it if/when this happens again.
