### ISSUE TITLE
Onboarding not showing

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#651]
WyriHaximus is kind enough to push the limits and find edge cases with our alpha :-)

He is not seeing the onboarding view, i.e badge settings, but a blank screen. This was after addressing an initial issue he ran into (https://github.com/polarsource/polar/pull/649). 

I believe this is likely due to the volume of repositories being installed at once.

**Comment by zegl** [comment]
Hehe, there is a few places where we need to add pagination to support handling more than 40 repositories. :D

**Comment by zegl** [comment]
@birkjernstrom I've pushed some reliability changes to this page and the endpoints, and it's working fine for me when testing with 200+ repositories now.

I'll close this now, please ask him to try again, and if it's still not fixed, we can re-open this issue. :)
