### ISSUE TITLE
Posthog: Events for pledge flow

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#660]
Events:
- Badge shown (SVG requested). _Not a perfect metric due to short-term cache, but good to have_
- Pledge page shown
- Pledge amount entered
- Email entered
- Form completed
- Submitted
- Status (Paid, Failed etc)

Variables:
- Organization ID + Name
- Repository ID + Name
- Issue ID + Number

**Comment by hult** [comment]
I guess you want to make a funnel for these events. #709 implements them, but the "Pledge Badge Shown" event won't be for an identifiable user (as it is generated on the next server, and not requested from the web app), so it can't really go in the funnel.

**Comment by hult** [comment]
Badge shown event moved to #723
