### ISSUE TITLE
Pledge behind any issue

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#661]
https://github.com/orgs/polarsource/discussions/562

**How it should work**
1. `/new` offers input to add a Github issue link
2. Our backend parses it and adds all the entities (org, repo, issues)
3. Responds with a redirect_url to the pledge page

Our pledge page will handle it from there.

**Remaining:**
- [ ] Post a Github comment using "polar-sh" user

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/661">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/661/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/661/pledge.svg">
</picture>
</a>

**Comment by hult** [comment]
#728 addresses the /new part

**Comment by hult** [comment]
#734 allows for more anonymous requests

**Comment by hult** [comment]
#737 moves the org/repo/issue creation to the pledge page and makes `/new` accept a `link` query parameter
