### ISSUE TITLE
Uninstalled organizations cannot be re-installed

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#701]
**Reproduce**
1. Install an organization w. repos
2. Uninstall it from Github so it has a timestamp in `organizations.deleted_at`
3. Install it again. You'll get stuck with "Connecting repositories" in the initialize onboarding view.

Manually removing the `deleted_at` and refreshing the page makes it work.

**Comment by hult** [comment]
I think this is because we upsert the org in the org service's `install` method, but upsert won't affect the `deleted_at` flag

**Comment by zegl** [comment]
I stumbled upon this in #694 as well. I have a commit in there that I can cherry pick. :-)
