### ISSUE TITLE
Support Open Collective for Maintainers

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#712]
**Background**
Several maintainers have requested to use Open Collective instead of Stripe, e.g collective of maintainers using OC as their fiscal host. I chatted with OC and am glad to share that they're excited to support Polar through the same setup/flow they have with Github today. 
* Maintainers can link their OC account (URL) to Polar vs. Stripe
* Inbound pledges work as normal, i.e goes to the Polar Stripe platform account
* Once completed we don't transfer it using Stripe Transfer API (via backoffice).
* Instead, we:
   - Highlight it as "Open Collective" in our backoffice instead of Stripe actions
   - Run a monthly report to export all such outstanding balances to be paid to Open Collective (outside the scope of the initial task here – we'll do that ad-hoc in partnership with OC)

### Considerations & limitations
* We should expand our `accounts` model to support + introduce types, e.g `stripe` & `open_collective`
* We should only support one `active` account per organization, i.e it's either or, but multiple records can exist with one active. _Note: Supporting changing accounts via UI is outside the scope for this issue. Will require support outreach + help_
* Required fields across both will be `country`, `currency` & `business_type`. For OC, we'll prompt the maintainer to specify theirs as with Stripe. For `currency` we'll hardcode it to `USD` and `business_type` as `fiscal_host`
* `is_details_submitted`, `is_charges_enabled` & `is_payouts_enabled` are quite nice to leverage for OC as well to standardize the model/usage in the future. However, they will default to `true` for valid OC submissions.

#### Setup
`https://polar.sh/finance/:org_slug:`

**Current**
<img width="905" alt="image" src="https://github.com/polarsource/polar/assets/281715/d1950ab8-b7f3-43a4-8c5e-1bdaf42327ec">

**Changes to be made**
* Bonus: Fix "Setup up Stripe" to "Setup Stripe" 😅
* Change copy to "You need to setup **Stripe** or **Open Collective** for payouts"
* Change button to "Setup" (onClick opens the next module as it does today) 

<img width="910" alt="image" src="https://github.com/polarsource/polar/assets/281715/d5717796-2f63-46b8-952a-93d000bc51ca">

**Changes to be made**
* Add dropdown to choose between `Stripe` & `Open Collective`. This should be before current country dropdown. Stripe as the default.
* Move country explanation, e.g "If this is a personal account", below the country dropdown. Make it `text-xs`
* If Stripe: That's it. "Setup account" links to Stripe as is today.
* If OC: Add Input for Open Collective URL.
  - Label: "Open Collective Profile URL"
  - Input
  - Explanation below (text-rs): "Example: https://opencollective.com/curl" 
  - On "Setup account". Parse, validate & save. Close modal to return to financial view (next).

#### Review finances

<img width="915" alt="image" src="https://github.com/polarsource/polar/assets/281715/71a83910-76b5-4758-994c-a7065c9f1794">

**Changes to be made**
* If Stripe: Keep as is
* If OC:
  - Change icon to OC icon
  - Copy: "Payouts will be sent in bulk once per month to the connected Open Collective account"
  - "Go to Open Collective". Link to the OC profile URL.

### Expected Backoffice UX

URL: `https://polar.sh/backoffice/pledges`

<img width="1425" alt="image" src="https://github.com/polarsource/polar/assets/281715/d53eaad3-1130-4490-a239-0a0c7e1e5c17">

**Changes to be made**
We'll start simple here. As we do our first payouts with OC and have the operational flows setup in collaboration with them, we'll learn and refine this. For now, let's first make sure we clearly see it's OC vs. Stripe.
* Add column to table. "Account" with `Stripe` vs. `Open Collective` for these pledges in terms of the receiving account
* Keep actions (buttons) for Stripe. Replace them for `Open Collective` with "Manual Open Collective Payouts"

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/712">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/712/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/712/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
Thank you for the detailed explanation and changes to be made. That's crystal clear!

You confirm that, for now, it's just a "declarative" setup on the user's side? I see OC has an open GraphQL API to query [Collectives](https://graphql-docs-v2.opencollective.com/queries/collective). Wouldn't it be interesting to have a sanity check that verifies that the collective at least exist on their side?

**Comment by birkjernstrom** [comment]
> Thank you for the detailed explanation and changes to be made. That's crystal clear!

Awesome 🤓

> You confirm that, for now, it's just a "declarative" setup on the user's side? I see OC has an open GraphQL API to query [Collectives](https://graphql-docs-v2.opencollective.com/queries/collective). Wouldn't it be interesting to have a sanity check that verifies that the collective at least exist on their side?

Confirmed. That was the initial intent & still a satisfactory implementation at this stage. No fraud vectors of providing an inaccurate one that I can think of & in the interest of maintainers to have a real one. So doubt we'll see erroneous submissions at all except a potential typo. So we can start there.

However, I definitely agree nonetheless that a sanity check is interesting & offers a more friendly confirmation/error to the UX. So it's a nice bonus if it's a quick addition. _I'll check with the OC team quickly on this too and get their input. Some fields in the GraphQL response that are interesting & might have some importance to us_

**Comment by birkjernstrom** [comment]
Chatted with the OC team. We should verify against the API to ensure:
- Collective is active, e.g not frozen, inactive etc.
- Collective is _fiscally hosted_ by [OSC](https://www.oscollective.org/). Otherwise, they're ineligible for this integration, i.e likely using Stripe or something else themselves.

I'm chatting with their CTO to confirm the exact specifics on how to best verify this and will circle back once I have that context.

**Comment by frankie567** [comment]
Thank you for the information about OC API! I'll look into that when we have the basic implementation.

I have an interrogation regarding pledges listing in the backoffice. Currently a `Pledge` is linked with an `Organization`. So, to display the account type (i.e. Stripe or OC) in the listing, we need to retrieve the associated `Account` of the `Organization`.

---

As you mention in the issue summary, an `Organization` can be linked to multiple `Account`, with only one being `active`. However, currently, the `Status` enum only supports two values: `CREATED` and `ONBOARDING_STARTED`.

https://github.com/polarsource/polar/blob/290a9cfc80ff4ca1635d97a59a24b29c42717770/server/polar/models/account.py#L17-L19

This status doesn't seem to be used in the API or the UI (and I didn't find a place where it's actually updated after a successful Stripe onboarding). Currently, we just consider the first account:

https://github.com/polarsource/polar/blob/290a9cfc80ff4ca1635d97a59a24b29c42717770/clients/apps/web/src/components/Finance/Finance.tsx#L253

---

So, if we want to improve this, the following changes are needed IMO:

* Add an `ACTIVE` status to the `Status` enum.
* On successful Stripe onboarding or OC setup, set `Account.status` to `ACTIVE`.
* On the UI, retrieve the `ACTIVE` account of the organization (instead of the first one)
    * Similarly, we'll then be able to do this to retrieve the account for each pledge in the backoffice

Let me know what you think about this :)

**Comment by birkjernstrom** [comment]
Fantastic summary @frankie567! Super helpful and clear.

Yes, I completely agree with the proposal of introducing an "active" status for accounts and using it.

Interesting with the other statuses not being used; it could be a potential regression. In case of Stripe onboarding, in case the user didn't complete it and returned to our dashboard we would show "Continue setup". I don't recall exactly how this was determined, but sounds very relevant to the existing statuses. However, it could be that we use the state of another column in that table. I'll investigate a bit too when I'm by a computer.

**Comment by frankie567** [comment]
Great!

Actually, it seems we currently use `is_details_submitted` to check the setup state of Stripe. It works, but it would probably more generic to rely on our own states for this.

**Comment by frankie567** [comment]
@birkjernstrom Sorry, after having a fresher look, it looks like an `Organization` can have only *one* `Account`. There is a constraint for that:

https://github.com/polarsource/polar/blob/1d3abef2e9d8e620c06903879a217b5d28ab7e41/server/polar/models/account.py#L23

And actually, this assumption stands in several parts of the code:

https://github.com/polarsource/polar/blob/1d3abef2e9d8e620c06903879a217b5d28ab7e41/server/polar/models/organization.py#L87-L89

https://github.com/polarsource/polar/blob/1d3abef2e9d8e620c06903879a217b5d28ab7e41/server/polar/pledge/service.py#L628-L637

It looks pretty sensible to me. Is there a use-case where an `Organization` would need to have several accounts?

Keeping it like this easily solves the problem with displaying the account type in pledges list. Nevertheless, I still think an *active* status is a good idea.

**Comment by birkjernstrom** [comment]
Given the constraint, I completely agree we can leave it as is and keep enforcing one account 👍🏼

And no worries at all @frankie567 – I love these updates and how efficiently you're Sherlock Holmes:ing the code without any documentation 🙂🙏🏼  It's also helpful to me; it's been a while since I was personally in that part of the code so memory is a bit dusty and somethings have changed. Therefore, if anything I'm sorry for not proactively seeing these snags ahead 🙂
