### ISSUE TITLE
Billing Page

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#718]
Going beyond emails and gathering all financial activity in one convenient place.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/718">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/718/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/718/pledge.svg">
</picture>
</a>

**Comment by kdeldycke** [comment]
May I suggest looking at https://github.com/getlago/lago as a place to centralize anything billing-wise? 🤗

**Comment by birkjernstrom** [comment]
@kdeldycke Thanks for the suggestion - Lago seems awesome. For now, we actually solved this one for the current scope and feature set within Polar so will close this issue. However, I'll look into Lago further for future needs. 

At quick glance, I assume Lago is mainly focused on being a platform for suppliers to immediately bill their end-users. Versus in our case, we're more of a "marketplace" model with three parties; Polar, maintainers (supply) and backers (demand – those paying). Nonetheless, might be able to make it work and I'm all for finding smart ways to avoid building "table stake" features for our own product. So will definitely explore more.
