### ISSUE TITLE
Onboarding: Upsell badge of individual issue

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#721]
Objective: Show an upsell card to maintainers for repositories with badge setting by label & no active badges across their issues.

**Depends on: ** https://github.com/polarsource/polar/issues/656

**Comment by petterheterjag** [comment]
Design: https://www.figma.com/file/XyFpx0vdHk6bfWYLWmOHSC/Polar-Mega-File?type=design&node-id=2927-78051&mode=design&t=o9LsvH7tHBt9JZsY-4
