### ISSUE TITLE
Design Rewards

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#764]
![Image](https://github.com/polarsource/polar/assets/281715/310cbbc2-70dc-4e39-9df8-0a16bcb9c3db)

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/764">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/764/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/764/pledge.svg">
</picture>
</a>

**Comment by petterheterjag** [comment]
Design for "Finance" page: https://www.figma.com/file/XyFpx0vdHk6bfWYLWmOHSC/Polar-Mega-File?type=design&node-id=2870-77723&mode=design&t=o9LsvH7tHBt9JZsY-4

**Comment by birkjernstrom** [comment]
Moving this to build issue here https://github.com/polarsource/polar/issues/895
