### ISSUE TITLE
Bug: Badging

### ISSUE THREAD

**Issue by JacobCoffee** [polarsource/polar#778]
When manually badging an issue

---
![image](https://github.com/polarsource/polar/assets/45884264/57207cba-32e9-42eb-a5a9-97a017f21b09)
---
I did not see the pledge button pop up, just the label added

![image](https://github.com/polarsource/polar/assets/45884264/ee212183-6c2b-4c58-9004-de7cf804a3b9)
---
I edited the badge with a custom message, and it showed up, but it links to the image and not the pledge

---
![image](https://github.com/polarsource/polar/assets/45884264/baf3dc77-ed4e-4b9d-89d1-3aca2bc942c0)
---
I think this is odd because the anchor href looks right?
```html

<!-- POLAR PLEDGE BADGE START -->
Pledge your support for Pydantic v2!

<a href="https://polar.sh/litestar-org/litestar/issues/1708"><picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1708/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1708/pledge.svg">
</picture>
</a>
<!-- POLAR PLEDGE BADGE END -->
```

Pledge your support for Pydantic v2!

<a href="https://polar.sh/litestar-org/litestar/issues/1708">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1708/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1708/pledge.svg">
</picture>
</a>

https://github.com/litestar-org/litestar/issues/1708

**Comment by zegl** [comment]
Hey @JacobCoffee. Thanks for opening the issue, and the great debugging!

I did some testing and it looks like the issue comes from the lack of a newline between the `<a>` and the `<picture>`. I'm guessing it's freaking out GitHubs markdown parser somehow. 😅

**Comment by zegl** [comment]
A fix is out now, if you remove and add the `polar` badge again the link should get fixed. :-)
