### ISSUE TITLE
Ability for maintainers to customize the pledge minimum

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#812]
**Problem**
- Polar has a minimum requirement of $20 for backers to pledge
- Not always the best default for all initiatives
- Maintainers cannot customize it for their audience

**Solution**
- Keep a minimum, but...
- Allow maintainers to customize it in their organization settings
- Let's still have $1 as the absolute minimum to avoid badges with cents (famous last words). _Also note: Service fees to cover Stripe fees will still apply and are a higher (%) tax on smaller pledges due to the fixed ¢30_

**Additional context**

<img width="1130" alt="image" src="https://github.com/polarsource/polar/assets/281715/8cc7b52b-020a-4cef-ae0b-1a2fd323fc47">

_From our [Discord discussion](https://discord.gg/7HKRAEHN)_

**Comment by birkjernstrom** [comment]
@petterheterjag I think we can add this nicely by customizing our current badge settings:
- Change settings to have labels on the left & action on the right-hand side, meaning...
- **Show amount pledged** is a label left-aligned to the issue example with a on/off Switch right-aligned 
- "Minimum pledge amount" as the new setting with a small number input right-aligned with $20 as the default

WDYT? 

<img width="784" alt="image" src="https://github.com/polarsource/polar/assets/281715/5f4f96e7-32b6-4460-ad17-4f76e804fe21">

**Comment by petterheterjag** [comment]
Makes sense to me 👍
