### ISSUE TITLE
Toast low contrast in dark mode

### ISSUE THREAD

**Issue by zegl** [polarsource/polar#838]
![Screenshot 2023-07-06 at 11 06 03](https://github.com/polarsource/polar/assets/47952/e59254a5-f264-4190-adb0-cbb524187e59)

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/838">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/838/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/838/pledge.svg">
</picture>
</a>

**Comment by Mahmoudgalalz** [comment]
@birkjernstrom I will also send a different PR with this
Thanks @zegl

**Comment by ashharr** [comment]
I am working on this issue. Can you please assign it to me?

**Comment by birkjernstrom** [comment]
Awesome, thanks @ashharr! Assigned it over now

**Comment by birkjernstrom** [comment]
Hey @ashharr do you still have bandwidth and want to contribute on this one? No problems otherwise, I'll remove you as the assignee then.
