### ISSUE TITLE
Race condition of repository installation & issue synchronization

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#877]
We have a known race condition for installing & synchronizing repositories. It's triggered twice:
1. GitHub webhook event: `installation.created`
2. By user during initialization (UI) upon being redirected back to Polar post-installation.

We need to support both since `#2` is not guaranteed. Simultaneously, `#1` is required to give instant feedback and real-time feedback to end-user, and sometimes `#2` is delayed.

This has worked fine: 1) No issues & 2) Average number of issues per repository is not too high so despite this we're still only using a fraction of our rate limit.

However, recently we ran into an issue for the first time (Sentry Issue ID: 4324443250) of an `IntegrityError` exception during task `github.issue.sync.issue_dependencies`. Mostly, we use upserts, but for dependencies we do need to do individual API calls so we fallback on the typical get or create pattern.

Unfortunately, the UI installation `#2` attempted to synchronize the exact same dependency at the same time as `#1`. Causing the `IntegrityError`.

Simultaneously, it was for a repository with 1.5k issues so since we ran it twice it almost consumed all of our rate limit for the installation.

/End of debugging context :-)

**Solution**
We still need to support `#1` and `#2`, however we should introduce a lock mechanism so only one can initiate it.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/877">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/877/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/877/pledge.svg">
</picture>
</a>

**Comment by frankie567** [comment]
So, if I understand correctly, the problem comes down from here:

https://github.com/polarsource/polar/blob/3f2cf7ed4e51384de14bb776f09b16f1937a9513/server/polar/integrations/github/service/organization.py#L280-L289

When we hit this race condition, both server and worker try to create this `Repository`. The one who runs in second place triggers an `IntegrityError`. Right?

I'm probably not aware of all the implications around this chunk of logic but, wouldn't it be enough to just catch the `IntegrityError` and then move on?

**Comment by zegl** [comment]
> wouldn't it be enough to just catch the IntegrityError and then move on?

Yeah, I think that solves it. We can do that for creating orgs, repos, and issues in `sync_external_org_with_repo_and_issue`.


I also think that it could be a good idea to limit how often these bigger sync jobs should be able to run, to help mitigate the other problem in that we're consuming a lot of API calls and reaching the request limits for some larger installations.

We could limit the jobs `github.repo.sync.issues` and `github.repo.sync.pull_requests` to not be allowed to run concurrently or in quick succession of each other. Both of these jobs will crawl GitHub to find issues/PRs, process them, and then create even more background jobs.

We could have a mechanism to skip the crawling if the job was recently started (within one hour?) for that same repository. The way from the two entry points that Birk mentioned above only one will cause a full sync, and the other will be skipped.

**Comment by birkjernstrom** [comment]
Agree with all of the above and especially the clarification from Gustav's recommendation. 

I'd be curious whether `arq` has built-in support to limit task frequency. Otherwise, perhaps it's something we implement as a centralized feature in our `enqueue_job` based on the task name and arguments? 

Would be nice to use such logic even for the badge tasks as well potentially (separate issue though and outside the scope of this).
