### ISSUE TITLE
Some issues are not badged

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#878]
I've encountered two repositories with issues that are expected to be badged, but are not for some reason... Not great.

Need to investigate and fix.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/878">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/878/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/878/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
One of them (`833dfe5e-bcdd-486a-a6e1-2a1678c850cf`) was due to `onboarded_at` not being set on the organization.

**Comment by zegl** [comment]
Closing this for now. If it happens again we can open a new issue.
