### ISSUE TITLE
GitHub Promotion

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#900]
FR https://github.com/orgs/polarsource/discussions/569

Design & ship our "GitHub" promotion page in the maintainer dashboard.
![IMG_1761 Large](https://github.com/polarsource/polar/assets/281715/a227cbc3-1879-47fa-a05e-c9cb68dccea8)

### Features
* GitHub badge (Shields.io) to link towards their Polar maintainer page
* SVG highlighting issues to fund on Polar to embed on their README (copy/paste embeddable)
* CTA to add the Polar maintainer page to their funding.yml to show up under "Sponsor this project"
* Potentially: Move customization of badge context to this view

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/900">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/900/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/900/pledge.svg">
</picture>
</a>

**Comment by petterheterjag** [comment]
Design: https://www.figma.com/file/jk6bG8H9YDlW2g58fRAzAA/Polar-v0.2-%E2%80%93-v0.5?type=design&node-id=66-4746&mode=design&t=ao26SWpF10fIgfsh-4

**Comment by zegl** [comment]
Done in #940 #941 #942 #943 and #944
