### ISSUE TITLE
🎯 Support PayPal

### ISSUE THREAD

**Issue by birkjernstrom** [polarsource/polar#902]
Add support for funding using PayPal

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/902">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/902/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/902/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Unfortunately, this is not an easy lift at this stage. Stripe only supports PayPal integration for EU platforms at this stage – US support TBD. So we would need to build a custom PayPal integration.

**Comment by coopbri** [comment]
It sounds like it is difficult, but still planned? If so, can this please be reopened?
