### ISSUE TITLE
Broken email validation on the fund issue form

### ISSUE THREAD

**Issue by 12joan** [polarsource/polar#915]
## Description

When the email field on the [fund issue form](https://polar.sh/polarsource/polar/issues/915) is prefilled with or set to an email address that the system doesn't think is valid (including newer TLDs like `.studio`), the "Fund this issue" button is disabled with no validation message.

## Steps

1. Set your GitHub email address to something ending in a newer TLD (e.g. `hello@validdomain.studio`)
2. Go to the [fund issue form](https://polar.sh/polarsource/polar/issues/915) `https://polar.sh/:org/:repo/issues/:id`
3. "Fund this issue" button is disabled and no validation message is shown
4. Change the email address to use a more common TLD (e.g. `hello@validdomain.com`)
5. The rest of the form renders as expected

## Expectation

Usually, email addresses are validated based on their syntax rather than perceived semantic correctness, preventing issues like this where newer TLDs aren't recognised.

In addition, disabling the submit button of a form without providing a validation message explaining why is widely regarded as a usability issue. (Curiously, accepted wisdom ranging from [2015](https://ux.stackexchange.com/a/76306) to [2023](https://www.bennadel.com/blog/4419-the-user-experience-ux-of-disabled-form-buttons.htm) seems to be to keep buttons enabled and only show validation messages on submit. This isn't the pattern I usually go with in my apps, but it's worth bearing in mind that there's no clear consensus on industry standard.)

## Demo

https://github.com/polarsource/polar/assets/4272090/f5a4a26f-8289-4e0d-894a-157f7ef55a62

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/polarsource/polar/issues/915">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/915/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/915/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
Hey @12joan! Thanks for taking the time in creating a really nice bug report – I really appreciate it! :-)

The bug was coming from a naive regex that has now been removed with a simpler validation that looks for an `@` in the field before forwarding the data to the server. :)
