### ISSUE TITLE
Sort low contrast in dark mode

### ISSUE THREAD

**Issue by JacobCoffee** [polarsource/polar#952]
![image](https://github.com/polarsource/polar/assets/45884264/e055109c-66c3-4cb3-bd77-64ddc5c4835e)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/952">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/952/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/952/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
Thanks @JacobCoffee for submitting this 🙏🏼

I'm expecting a baby any second now 😍 So not sure I'll be able to ship a fix as quickly as I'd normally like. Adding `good first issue` in case someone wants to contribute a patch. Otherwise, I'll make sure to prioritize a fix as soon as possible for this.

**Comment by birkjernstrom** [comment]
What browser/OS was this @JacobCoffee ?

**Comment by JacobCoffee** [comment]
Windows, Firefox

Linux, Firefox works just fine fwiw

**Comment by ashharr** [comment]
I'm working on this issue. Can you please assign it to me?

**Comment by ashharr** [comment]
https://github.com/polarsource/polar/pull/1007

**Comment by ashharr** [comment]
@JacobCoffee This issue is fixed. https://github.com/polarsource/polar/pull/1007 was merged.

Thanks all,
Ashhar
