### ISSUE TITLE
Markdown preview inconsistencies when using markdown in HTML

### ISSUE THREAD

**Issue by niccokunzmann** [polarsource/polar#985]
If I use Markdown in an HTML tag, Polar will render it as markdown but Github will as plain text.

Example:
https://github.com/niccokunzmann/open-web-calendar/issues/12

![image](https://github.com/polarsource/polar/assets/564768/70158e3f-b75d-4c23-8c44-23baee603046)

Code:

<small>[text](https://link.com)</small>

This is a difference in expectation.
This poses the question: Does polar re-edit the sections to change the text?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/985">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/985/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/985/pledge.svg">
</picture>
</a>

**Comment by zegl** [comment]
Thanks for the bug report!

As you've noticed, the issue here comes when setting the custom badge message to something that wraps markdown in HTML, it will break on Github but not in our perview.

```markdown
<small>
[Polar.sh](https://polar.sh/)
</small>
```

A workaround for this is to not mix markdown and HTML, by making the whole message HTML:

```
<small>
<a href="https://polar.sh/">Polar.sh</a>
</small>
```

**Comment by zegl** [comment]
This has been fixed
